egallesio/STklos

- doc/skb/srfi.skb
- doc/skb/srfi.stk
- lib/Makefile.am
- lib/srfi-0.stk
- lib/srfi-51.stk
- tests/test-srfi.stk
I don't know what the criteria would be to include synonims in SRFI-0.
I have added this as "rest-list", but I'm not sure it's needed.
> Adds SRFI-51

- PORTING-NOTES.md
If more information on the tested hardware is needed, I am happy to change the PR.
> Add list of tested hardware to PORTING-NOTES

- INSTALL-android.md
This file contains instructions to compile in Android platforms.
@egallesio - is the format OK? Markdown i sgreat for processing and producing all kinds of output, but not the best thing to read. If you prefer, I can convert it to plain text.
> Add INSTALL-android

- src/ffi.c
- src/vm.c
No big deal, but cppcheck complains about these...
> Close va_list

- doc/skb/srfi.skb
- doc/skb/srfi.stk
- lib/Makefile.am
- lib/srfi-0.stk
- lib/srfi-117.stk
- tests/test-srfi.stk
This is SRFI-117; The tests from the SRFI itself are included!
> Add SRFI-117

- SUPPORTED-SRFIS
- doc/skb/srfi.skb
- doc/skb/srfi.stk
- lib/Makefile.am
- lib/srfi-0.stk
- lib/srfi-174.stk
- tests/test-srfi.stk
SRFI-174 here.
The tests are those which came with the SRFI.
Nothing complicated in this one...
> Adds SRFI-174 - POSIX Timespecs

- HACKING.md
Wouldn't it be nice if newcomers could more easily work on STklos? I thought that maybe a `HACKING.md` file would be a good idea. (No?)
Is markdown OK?
> Add a HACKING.md file

- SUPPORTED-SRFIS
- doc/skb/srfi.skb
- doc/skb/srfi.stk
- lib/Makefile.am
- lib/srfi-0.stk
- lib/srfi-161.stk
- tests/test-srfi.stk
> Adds SRFI-161 - Unifiable Boxes

- lib/srfi-0.stk
> More draft SRFIs

- doc/stklos.1.in
Also included some missing punctuation
> Add "-V" to the manpage

- SUPPORTED-SRFIS
- doc/skb/srfi.skb
- doc/skb/srfi.stk
- lib/Makefile.am
- lib/srfi-0.stk
- lib/srfi-175.stk
- tests/test-srfi.stk
Here's the ASCII character library!
> Add SRFI 175 - ASCII character library

- HACKING.md
- vm.md
Not complete, but already useful, I hope.
> Documentation for the virtual machine

- vm.md
Some more updates! :)
Probably, some important opcodes are missing yet. I am not sure...
And I couldn't find a way to write code that generates `DEFINE-SYMBOL`.
> Update to VM documentation

- SUPPORTED-SRFIS
- doc/skb/srfi.skb
- doc/skb/srfi.stk
- lib/Makefile.am
- lib/srfi-0.stk
- lib/srfi-185.stk
- tests/test-srfi.stk
Some people dislike this SRFI, but it may be interesting at least for compatibility (if one needs to run a program that relies on this SRFI, it would be easy if it were available).
> Add SRFI-185 - Linear adjustable-length strings

- SUPPORTED-SRFIS
- doc/skb/srfi.skb
- doc/skb/srfi.stk
- lib/Makefile.am
- lib/srfi-0.stk
- lib/srfi-189.stk
- tests/test-srfi.stk
Now that raise-continuable works, here's one more SRFI! :)
> SRFI 189 -- Maybe and Either: optional container types

- src/char.c
- src/env.c
- src/hash.c
- src/process.c
- src/sio.c
- src/vm.c
@egallesio I guess you got used to press ";" twice after so much Lisp coding... :)
> Remove double semicolon from C files

- lib/srfi-0.stk
Some were withdrawn, some went final, and some were renamed!
> Update SRFIs information in srfi-0.stk

- configure.ac
- doc/Makefile.am
- doc/stklos-script.1.in
(Debian packages want manpages for all executables)
> Add manpage to stklos-script

- doc/stklos-script.1.in
Sorry for that! Forgot the backslash in the previous commit...
> It's "#\space", not "#space"

- SUPPORTED-SRFIS
- doc/skb/srfi.skb
- doc/skb/srfi.stk
- lib/Makefile.am
- lib/srfi-0.stk
- lib/srfi-61.stk
- tests/test-srfi.stk
Just one extra condition in the compilation of COND gives SRFI-61... :)
> Add SRFI-61 - A more general cond clause

- SUPPORTED-SRFIS
- doc/skb/srfi.skb
- doc/skb/srfi.stk
- lib/Makefile.am
- lib/srfi-0.stk
- lib/srfi-196.stk
- tests/test-srfi.stk
Hello!
Would you be interested in SRFI-196 - Range Objects? :)
No issues with this one, it seems!
> Add SRFI-196 - Range Objects

- tests/test-srfi.stk
The only failing test is related to #141 .
Tell me if it's Ok. We should probably delete the tests that are commented out.
> Add tests for SRFI-4

- src/port.c
- tests/test-r7rs.stk
Also include a test...
This would fix #159
> write: check if port is textual

- lib/date.stk
- lib/srfi-170-impl.c
- lib/srfi-170.stk
- lib/srfi-174.stk
- src/system.c
@egallesio  -- I'll send individual commits for each remaining issue. Is this ok?
> SRFI-170 -- missing bits

- SUPPORTED-SRFIS
- lib/Makefile.am
- lib/srfi-217.stk
- lib/srfis.stk
- lib/trie.stk
- tests/srfis/217.stk
Here's SRFI-217. It is listed as "draft" in the SRFIs page, but it's final (Arthur did send the "Final SRFI" email to the mailing list, and the SRFI text itself says it's final).
This one only depended on the 2-args log, which was fixed today! :)
> Add SRFI 217 - Integer Sets

- lib/srfi-25-impl.c
The previous code was duplicating the mutex, making it useless. Now shared arrays do use the original array mutex.
This does not yet fix the share-counting error.
> Fix shared array ref to original lock

- HACKING.md
- README.md
- vm.md
Remove duplication in `HACKING.md`;
Mention MELPA in `README.md`
> Fixes to documentation

- lib/srfi-133/Makefile.am
- lib/srfi-175/Makefile.am
- lib/srfi-25/Makefile.am
> Typo in SRFI numbers

- SUPPORTED-SRFIS
- lib/Makefile.am
- lib/srfi-223.stk
- lib/srfis.stk
- tests/srfis/223.stk
Hi @egallesio ! One more SRFI...
The tests for this one depend on PR #242 (otherwise they'll enter a loop and never finish).
> Add SRFI-223: Generalized binary search procedures

- lib/library.stk
- tests/test-r7rs-lib.stk
First commit - nothing essential, just some typos!
Second commit - added some tests
> Fix typos in library.stk and add some tests

- lib/assembler.stk
* Fix documentation
* Print all output to the chosen port
> Small fixes to disassemble-expr

- lib/help.stk
- lib/http.stk
- lib/logical.stk
- lib/repl.stk
I'm not sure about the empty line in `repl.stk` (is it intentional?)
Also, I'm not sure the HTTP download procedure would be documented like that; does this make it go into the manual? If so, in which section?
If I got anything wrong tell me!
> Small aesthetic changes

- tests/test-r7rs-lib.stk
> More R7RS library tests

- doc/Makefile.in
- lib/Makefile.am
- lib/Makefile.in
- lib/srfi/132.c
- lib/srfi/132.stk
- lib/srfi/Makefile.am
- lib/srfi/Makefile.in
Now I've tried porting a mixed SRFI. I hope I got everything right...
> SRFI-132: now an R7RS library

- HACKING.md
- vm.md
I've written some more documentation... :)
> Updates to the internals doumentation

- SUPPORTED-SRFIS
- doc/Makefile.in
- doc/skb/srfi.skb
- doc/stklos-compile.1.in
- lib/compfile.stk
- lib/srfis.stk
- utils/stklos-compile.stk
This is SRFI-138, <s>but without the `-D` option... (See issue #293 )</s>!
> Add SRFI-138 - Compiling Scheme programs to executables

- lib/Makefile.am
- lib/Makefile.in
- lib/srfi/196.stk
- lib/srfi/Makefile.am
- lib/srfi/Makefile.in
I'm sending individual PRs for each migrated SRFI. If you prefer a single PR with several commits, tell me.
> SRFI 196: now as R7RS library

- lib/Makefile.am
- lib/Makefile.in
- lib/srfi/141.stk
- lib/srfi/Makefile.am
- lib/srfi/Makefile.in
> SRFI 141: now R7RS module

- lib/Makefile.am
- lib/Makefile.in
- lib/srfi/48.stk
- lib/srfi/Makefile.am
- lib/srfi/Makefile.in
I have tested, and it seems that it works even though SRFI 48 is embedded! :)
> SRFI 48 -> R7RS

- src/number.c
The error message when we tried to apply abs, floor,
positive? and similar procedures on a complex number was
"bad number", the same message as if it were a string,
symbol or anything not numerical. We can be more precise
in the error message, without performance penalty and
simplifying a tiny bit the file `number.c`.
This is what weget after this patch is applied:
```
stklos> (abs -1+2i)
**** Error:
abs: `-1+2i' is not a real number
stklos> (abs 'a)
**** Error:
abs: `a' is a bad number
stklos> (positive? -1+2i)
**** Error:
positive?: `-1+2i' is not a real number
stklos> (positive? "x")
**** Error:
positive?: `"x"' is a bad number
stklos> (floor …
```
> Differentiate "not a number" and "not a real number"

- lib/bonus.stk
- lib/describe.stk
This PR makes STklos more descriptive in describe.stk. :) Also fixes a typo in bonus.stk
> Enhance descriptions and fix a typo

- lib/srfi/25.stk
- tests/srfis/25.stk
A small thing, but I thought it would be nice to have...
> Add setters for SRFI-25 arrays

- lib/srfi/25.c
Thanks for noticing the other use of CLOSUREP and CLOSURE_ARITY @egallesio ! Fixed :grin:
> Use general procedure functions instead of CLOSURE*

- configure
ref: https://www.shellcheck.net/wiki/SC2283
> configure: use [ ] to compare values

- SUPPORTED-SRFIS
- lib/srfi/228.stk
- lib/srfi/Makefile.am
- lib/srfis.stk
- tests/srfis/228.stk
And also update the SRFI status in `srfis.stk`...
> Adds SRFI 228: Composing Comparators

- src/system.c
We used to use `- timezone` to get the offset in seconds, but it's not portable, so we use the new `tz_offset` function.
This resolves #451
> Use a portable way to get the timezone offset

- lib/library.stk
> Add support for include-library-declarations

- doc/hacking/hacking.adoc
- doc/vm/vm.adoc
- lib/peephole.stk
There were some imprecise descriptions in the text. Also added some more explanation.
> Expands and fixes VM documentation

- src/vm.c
This simplifies the code, and perhaps it's more interesting to do `vm->sp+=n` within `listify_top` than to call `pop()` (that is, do `vm->sp++`) several times. (?)
Also included some comments about the two functions.
> `vm.c`: use `listify_top` in `adjust_arity`

- SUPPORTED-SRFIS
- lib/srfi/235.stk
- lib/srfi/Makefile.am
- lib/srfi/Makefile.in
- lib/srfis.stk
- tests/srfis/235.stk
One more SRFI... It just became final! :grin:
> Add SRFI 235 - Combinators

- src/number.c
By using `mpz_init_set_d` (which the mini-gmp also supports).
Fix #469 
In order for this to work, we also move the more fundamental functions to an earlier position in the code, before `double2integer`:
- `bignum2integer`
- `bignum2double`
- `scheme_bignum2double`
- `scheme_bignum2real`
- `bignum2scheme_bignum`
- `bignum2number`
A small experiment:
```
;;; BEFORE
;;;
(let ((a 0))
(time (dotimes (i 10_000_000)
(set! a (exact 1180591620717411303424.0)))) a)
Elapsed time: 34188.079 ms      <== 34 seconds
1180591620717411468064          <== loss of precision
;;; AFTER
;;;
(let ((a 0))
(time (dotimes (i 10_000_000)
(set! a (exact 1180591620717411303424.0)))) a)
Elapsed time: 2897.31 ms        <== less than 3 seconds!
1180591620717411303424          <== precisely the same number!
```
Of …
> Make `double2integer` more efficient and precise

- lib/describe.stk
@egallesio - does this make sense?
> Describe keywords and characters more nicely

- doc/refman/stdproc.adoc
- lib/bonus.stk
- tests/test-number.stk
Inspired by Gauche...
Two trivial functions, but actually useful. :grin: 
(@egallesio I may need to slow down a bit in the next weeks, but I already have a couple of other PRs ready, so I'll send them tomorrow...)
> Add `radians->degrees` and `degrees->radians`

- src/number.c
And consequently, `exact`.
When the full GMP is available, we just turn the double into an `mpq_t` variable and get back the numerator and denominator.
Much faster than the current code:
```
(let ((a 3.1)
(b #f))
(time
(repeat 5_000_000
(set! b (exact a))))
b)
Current code: 14535.114 ms
This patch:    2461.519 ms  ==> Actually, 2105 ms, after using mpz_clear
```
This uses conditional compilation, since the mini-GMP does not have rationals.
There is another PR (#524) which also adds a primitive `%stklos-has-gmp?`
**edit**: I also added `mpz_clear` to several places in `number.c`.  It's of course required (we were leaking some memory), and also seems to make the code faster.
**edit, again**: I also noticed a speedup in `expt` with exact exponent.
> Optimize `double2rational` (and `inexact->exact`)

- src/stklos.h
Mostly typos and comment alignment changes.
> Cosmetic changes only

- tests/test-number.stk
Some tests for the cases you just fixed. :)
And also for the basic "square root of negative numbers"...
> Tests for sqrt of negative numbers

- lib/describe.stk
Nothing really important... Just be more informative when describing NaNs.
> More detailed description of NaNs

- src/number.c
- tests/test-number.stk
These patches fix some limits... I only noticed this when I saw a commit to Gambit fixing something similar (although in a very different way).
> Fixes hyperbolic trigs for lim(x -> infinity)

- NEWS.md
I opened a PR for the website, but I realise that the website news is generated from the NEWS file, so I think this is the right place for it (is that correct?)
> Fix typos in `README`

- doc/refman/stdproc.adoc
> Add `improper-list?` to the documentation

- tests/lib/scheme/bytevector.stk
Also remove some trailing whitespaces.
> Add subsection to libs testing

- lib/stklos/help.stk
Maybe not interesting, since the banner gets larger, but it also becomes more informative. :)
> Enhancement to help initial banner

- README.md
> `README.md`: STklos works on Linux 6.x

- tests/test-misc.stk
> Add tests for case-insensitive reads

- SUPPORTED-SRFIS
- lib/srfi/234.stk
- lib/srfi/Makefile.am
- lib/srfis.stk
- tests/srfis/234.stk
IT's great that we already have STklos 2.10!  Now, for the next release, here's one more SRFI... :grin:
> Add SRFI-234: Topological Sorting

- lib/bonus.stk
> Document `declare-new-error`

- SUPPORTED-SRFIS
- lib/srfi/258.stk
- lib/srfi/Makefile.am
- lib/srfis.stk
- tests/srfis/258.stk
This one is now final.
When it was proposed, another one was proposed as alternative (260, "Generated Symbols"). Both are very easy to implement, so I'd say we can have them both (do you disagree?)
> [simple] Add SRFI 258
