egallesio/STklos

examples/Makefile.am
lib/Lalr.d/Makefile.am
lib/Makefile.am
lib/ScmPkg.d/Makefile.am
pkgman/Makefile.am
src/Makefile.am
utils/Makefile.am
utils/tmpcomp

Hello!
This is to make it easier to cross-compile. I have used it to compile STklos for OpenWRT and run it on a wireless router (see here: https://gitlab.com/jpellegrini/openwrt-packages).
* Always use `COMP`, `STKLOS_BINARY`, `GENLEX` variables in
Makefile.am files, and honor their previous values
if they exist. This makes it easier to cross-compile:
having STklos locally installed, we may just do
```
COMP=/usr/local/bin/stklos-compile \
GENLEX=/usr/local/bin/stklos-gelnex \
STKLOS_BINARY=/usr/local/bin/stklos \
./configure && make
```
For this to work, the utils/tmpcomp script had to be
slightly modified, so it will accept the same arguments
as stklos-compile, with the '-o' switch (but with this
patch, it also works if called without it).

make cross-compilation easier

---

src/dynload.c
src/fport.c
src/gnu-getopt.c
src/process.c
src/sio.c
src/system.c
src/vm.c

No big deal, but makes gcc happier when running with --pedantic

Use va_end() after va_start()

---

doc/skb/srfi.skb
lib/Makefile.am
lib/srfi-0.stk
lib/srfi-1.stk
lib/srfi-173.stk
tests/test-srfi.stk

This is the example implementation from the SRFI, adapted to STklos.
One procedure was changed: instead of "assume" in hook-run,
an if followed by a call to error is done. This is consistent
with what is done in other SRFI implementations in STklos.
The tests are simple, but all procedures are tested.

Adds SRFI-173

---

lib/srfi-69.stk

In `srfi-69.stk`  there is this:
```
;; ======================================================================
;; Redefine make-hash-table and alist->hash-table to use equal? instead of
;; eq? as default comparison function
(define %old-make-hash-table make-hash-table)
(define %old-alist->hash-table alist->hash-table)
(define (make-hash-table :optional (comp equal?) (hash hash))
(%old-make-hash-table comp hash))
```
But that code redefines `make-hash-table` only, not `alist->hash-table`. I confirmed on the REPL:
```
stklos> (require "srfi-69")
"srfi-69"
stklos> (eq? %old-make-hash-table make-hash-table)
#f
stklos> (eq? %old-alist->hash-table alist->hash-table)
#t
```
And the `alist->hash-table` defined in `bonus.stk` uses `eq?` as default comparison predicate.
By the way, this affects the …

Redefine alist->hash-table in SRFI-69

---

lib/bonus.stk

Fix a typo in the ansi-color code names

---

doc/skb/srfi.skb
doc/skb/srfi.stk
lib/Makefile.am
lib/srfi-0.stk
lib/srfi-171.stk
tests/test-srfi.stk

This is SRFI-171, Transducers.
The reference implementation has one single procedure (`tremove-duplicates`) which uses hash tables, allowing the user to pass an arbitrary equality predicate. Tests wouldn't pass in STklos, so I adpted it: if the predicate is `eq?` or `string=?`, then pass `hash-table-hash` to `make-hash-table`, otherwise, use the identity `(lambda (x) x)`.
I have included one more test, for `tremove-duplicates` with `string=?`.

Adds SRFI-171

---

doc/skb/srfi.skb
doc/skb/srfi.stk
lib/srfi-0.stk
tests/test-srfi.stk

STklos already supports SRFI-87 out of the box, as part of
R7RS support. This commit only documents it, and adds a
couple of tests to test-srfi.stk (besides the tests already
in test-r7rs.stk).

SRFI 87 already supported - document it

---

SUPPORTED-SRFIS
doc/skb/srfi.skb
doc/skb/srfi.stk
lib/Makefile.am
lib/srfi-0.stk
lib/srfi-156.stk
tests/test-srfi.stk

There was one macro which the reference implementation contains, using `syntax-rules`, which did not work in STklos, so I write another, using `define-macro`. All tests pass.
* the problem was that STklos introduces identical symbols in different phases of macro expansion using syntax rules:
```
(define-syntax f
(syntax-rules (k)
((f) #f)
((f k) 'K)
((f k x ...) (a (f x ...)))))
```
Here's the STklos expansion:
```
stklos> (macro-expand* '(f k k k))
(a (a 'K))
```
some other implementations will return
```
(a.0 (a.1 'K))
```
Anyway, not a problem, since we have `define-macro`!

Add SRFI-156 - Syntactic combiners for binary predicates

---

lib/srfi-13.stk
tests/test-srfi.stk

I found these while working on SRFI-130...
* SRFI-13 should export `string-trim`, there is no `string-trim-left`
* in string-trim, the arguments to `%check-indexes` were in wrong order
I included a few tests, not yet complete (we can add more later)...

Fix a couple of SRFI-13 bugs

---

SUPPORTED-SRFIS
doc/skb/srfi.skb
doc/skb/srfi.stk
lib/Makefile.am
lib/srfi-0.stk
lib/srfi-129.stk
tests/test-srfi.stk

I suppose it would make sense to use SRFI-129, since it is more general than the already present `string-titlecase` in STklos, and it offers two more procedures for characters. The tests added have a couple of comment marks at the end of the line, like this:
```
(test "string 3" "Ss" (string-titlecase "\x00DF;"))         ;
```
to show where this SRFI implementation differs from the embedded `string-titlecase` in STklos.
This SRFI exports
```
char-title-case?
char-titlecase
string-titlecase
```
One thing: if I create the module and export `string-titlecase`, the old one (defined as a primitive) will still be used, so I had to export a procedure `%string-titlecase` and later, after importing `SRFI-129` into the `STklos` module, redefin it:
```
;; If we just define the new string-titlecase …
```

Add SRFI-129 - Titlecase Procedures

---

SUPPORTED-SRFIS
doc/skb/srfi.skb
doc/skb/srfi.stk
lib/boot.stk
lib/srfi-0.stk
src/stklos.c
tests/test-srfi.stk

This adds SRFI 176, version flag.
I included the code in boot.stk -- so Scheme instead of C, because it would be easier.
I'm not sure what other information could be printed.
Please tell me if there is interest in this, and if it's implemented in a way you think is OK.
There are two SRFI PRs pending, and they both change `srfi-0.stk`, `doc/skb/srfi.stk` and	`doc/skb/srfi.skb` . If you accept one, the other will start conflicting, maybe -- I'll update then.

Add SRFI-176 - Version flag

---

SUPPORTED-SRFIS
doc/skb/srfi.skb
doc/skb/srfi.stk
lib/srfi-0.stk
src/str.c
tests/test-srfi.stk

This adds two procedures, written in C and placed in
str.c:
* string-append!
* string-replace!
An auxiliary function get_substring_size() was added also.

Add SRFI-118 - Simple adjustable-size strings

---

lib/mbe.stk

* When using `gensym`, pass it the symbol, so the generated symbols will be a bit easier to understand when debugging
* Add documentation to some procedures. Until another macro system is in place, we could enhance the documentation of this one a little bit. :)

Small enhancements to hygienic macro code

---

vm.md

The `DEFINE_SYMBOL` opcode seems to only be used in top level, so it's impossible to make an example with`disassemble`, right?

Some more updates on the VM documentation

---

SUPPORTED-SRFIS
doc/skb/srfi.skb
doc/skb/srfi.stk
lib/Makefile.am
lib/srfi-0.stk
lib/srfi-128.stk
tests/test-srfi.stk

Only one test from the SRFI reference implementation doesn't pass:
```
test 102 on (= (comparator-hash default-comparator "t") (string-hash "t")) expected #t but got #f
```
However, if I do it on the REPL,
```
stklos> (load "lib/srfi-128.stk")
stklos> (define default-comparator (make-default-comparator))
;; default-comparator
stklos>  (= (comparator-hash default-comparator "t") (string-hash "t"))
#t
stklos> (comparator-hash default-comparator "t")
26797187
stklos> (string-hash "t")
26797187
```
So I don't know what's happening...

Add SRFI-128 - Comparators (reduced)

---

tests/test-srfi.stk

Should not have redefined string-hash and char-hash.

Fix interaction between SRFIs 113 and 128 during tests

---

QUICK-INSTALL.md
src/Makefile.am

When cross-compiling, the strip binary will not work on the stklos
executable (binary format mismatch). One solution is to use a STRIP
variable, and set it to "stklos" if it is either missing or empty.
Tested on Debian GNU/Linux on amd64, and on the OpenWRT build root
(for MIPS).

Use an env var for strip

---

lib/Lalr.d/lalr.stk
lib/SILex.d/silex.scm

One more issue detected by the Debian packaging tools... Two files use ISO-8859-1 instead of UTF-8. This PR converts them to UTF-8.

Change encoding to UTF-8

---

src/Makefile.am

* Remove git-info.h, not git-config.h
* Also remove boot.ok
* And fix the comment in Makefile.am

Make clean really clean in src/

---

lib/Makefile.am

I am not sure if this is correct, but it seems to work!
This addresses bug #115 which has been brought up when packaging for Debian.

Install .so files in lib/

---

lib/srfi-2.stk

This would solve the copyright issue with SRFI-2. It is a recent (2020) implementation by Marc Nieper-Wißkirchen.
It is currently in the SRFI-2 repository in github, https://github.com/scheme-requests-for-implementation/srfi-2/tree/master/contrib

Update SRFI-2 implementation

---

lib/srfi-64.stk

Procedure %test-approximate= is used by macro test-approximate=,
but wasn't being exported

Export a procedure used by a macro in SRFI-64

---

lib/srfi-1.stk

I found this while preparing SRFI-134.
In `list=`, the reference implementation has a loop as this:
`(let lp2 ((pair-a list-a) (pair-b list-b))`
The STklos version had
`(let lp2 ((list-a list-a) (list-b list-b))`
but this makes the original list-b not accessible from inside the
loop, so for example
`(apply list= char-ci=? '((#\a #\b) (#\A #\B) (#\a #\B)))`
would fail when it should not.
This commit reverts to the reference implementation version of
`list=`.

Fix list= in SRFI-1

---

tests/test-srfi.stk

Not complete yet. These were adapted from Larceny to Chicken,
and now to STklos.
The Guile test suite is more complete, but also longer and it uses a different test framework; it would be harder to port.

Add tests for SRFI-1

---

src/uvector.c

The condition for setting values was swapped in both
(signed vectores did not accept signed numbers, and
unsigned vectors did)
Fix #141

Fix u64/s64 vectors mixup

---

src/number.c
tests/test-number.stk

Motivation: the tests for SRFI 194 (random data generators) use this, and several Scheme implementations accept it also (Guile, Racket, Chibi, Chicken, Gauche, Chez).
Using the inexact flag, the reader now accepts
#i0/1    => 0.0
#i2/3    => 0.666666666666667
#i1+2/5i => 1.0+0.4i
#i1@1    => (make-polar 1.0 1.0)
but it will *not* accept fractions made with floats, such
as
1/2.0
1/2.
1.0/2
I also uncommented some unrelated tests from the number test suite which actually pass (!)

Let reader accept #i for rationals

---

src/read.c
tests/test-misc.stk

STklos accepts `#T` and `#t`, but only `#f` (and not the uppercase `#F`); there
was a duplicate test for lowercase `#f`.
Also add tests for sharp syntax.

Fix uppercase for "#F"

---

lib/Makefile.am
lib/srfi-41.stk
lib/srfis.stk
lib/streams-derived.stk
lib/streams-primitive.stk
tests/srfis/41.stk

So, here is SRFI-41!
But I have some remarks. 
* modified to not use R6RS records
* one macro was taken from Chibi, because the reference implementation uses syntax-case
* I have created three modules, "streams-primitive", "streams-derived" and "srfi-41", which loads the other two. But I only included "srfi-41" in SRFI-0. I suppose it would be nice to have "srfi-41 primitive" and "srfi-41 derived", but I'm not sure. What do you think?
* Also corrected a little problem in SRFI-0 (SRFI-41 did not disappear! And SRFI-40 was withdrawn...)
* In order to take full advantage of the tests written by the original author, I have redefined (temporarilly) the error procedure, so it will print the error and continue (the tests actually match the exact error string)
And a more complicated one:
* I had …

Add SRFI-41 - Streams

---

src/misc.c

(gc) actually performs a garbage collection step, calling libgc's GC_gcollect() function.

Fix documentation of (gc) primitive

---

lib/Makefile.am

This makes cross-compilation much easier.

Use $(STKLOS_BINARY) instead of hardcoded path

---

SUPPORTED-SRFIS
lib/boot.stk
lib/srfis.stk
src/fixnum.c
src/stklos.h
tests/srfis/143.stk

This is a pull request, but consider it also a question: how do you feel about unsafe optimizations for fixnums (and possibly flonums later)?
I have implemnted SRFI-143 (fixnums), fully -- including the "/carry" procedures.
Now, the SRFI mentions that implementations can -- if they want -- skip type checks for these procedures, in order to run faster. 
So, I have ran one simple loop in three different ways:
1. using standard Scheme procedures
2. using fx... procedures as they are currently implemented in STklos
3. using fx... procedures without type checks
The loop is this:
```
(define n 100_000_000)  ;; look, there are underscores in the numbers ! :)
(define (sum n)
(let ((s 0))
(dotimes (i n)
(set! s (- (+ (- s) (* 2 i)) 5)))
s))
(define (fxsum n)
(let ((s 0)) …
```

Adds SRFI-143 - Fixnums

---

lib/Makefile.am

Otherwise the presence of a `stklosrc` file may break compilation.
This would fix #168 
I have tested and it seems to work...

Use -q when calling STklos

---

SUPPORTED-SRFIS
lib/Makefile.am
lib/srfi-170-impl.c
lib/srfi-170.stk
lib/srfis.stk

I think it's mostly done, there are just a couple of questions and small issues to be dealt with.
Tell me what you think about the proposed changes in core -- I can change this PR to include them.
* We need to raise errors reporting `errno`, so:
* the FFI was not used, since we cannot check `errno` with it;
* some procedures, like `file-directories`, were re-written
in srfi-170-impl.c.
* I wrote a new    `&posix-error` condition with slots for several data as recommended per the SRFI. It can be creted in Scheme as
```
(make-condition &posix-error
'procedure procedure
'args args
'errname (%get-posix-error-name errno)  ; a symbol with the same name as the C constant
; describing the error (for instance, `'EINVAL`)
'message (posix-get-message-for-errno errno)
'errno errno) …
```

Add SRFI 170 -- POSIX API

---

SUPPORTED-SRFIS
lib/Makefile.am
lib/describe.stk
lib/srfi-25-impl.c
lib/srfi-25.stk
lib/srfis.stk
src/boolean.c
src/stklos.h
tests/srfis/25.stk

I have tried to make this one as efficient as possible, while keeping the code clean.
And I have implemented several extra procedures. See below...
Also included are the following procedures from the array library
proposed by the SRFi author, Jussi Piitulainen:
```
;;; (array-shape arr)
;;; (array-length arr dim)
;;; (array-size arr)
;;; (array-equal? arr1 arr2)
;;; (shape-for-each shp proc [ind])
;;; (array-for-each-index arr proc [ind])
;;; (tabulate-array shp proc)
;;; (tabulate-array! shp proc ind)
;;; (array-map [shp] proc arr0 arr1 ...)
;;; (array-map! arr [shp] proc arr0 arr1 ...)
;;; (array->vector arr) (array->list arr)
```
And some others:
```
shared-array?
array-share-count
array-copy+share
```
I did not document the SRFI procedures, but there are extra …

Add SRFI-25: Multi-dimensional Array Primitives

---

lib/srfi-25-impl.c
tests/srfis/25.stk

Now the user cannot create shared arrays that are incompatible with the original array shape (leading to out of bound indices).
* I have made functions to show sequences of numbers and to show the mapping as strings. Then, I used `math.h` (and `-lm`, which STklos would already use anyway) to calculate the needed space for them. Is that OK?
* Added some tests for wrong shapes
* I have tried to make a reeeealy informative message. see:
```
stklos> (require "srfi-25")
"srfi-25"
stklos> (define a (make-array (shape 0 2 0 3) 'z))
stklos> (share-array a (shape 0 3) (lambda (x) (values x x)))
**** Error:
share-array: Shape (0 3) does not map to shape (0 2 0 3) under mapping x_0 -> 1y_0; x_1 -> 1y_0. Index (2) for the new array goes out of bounds in the original array.
stklos> (share-array a …
```

SRFI 25: add shape checking when creating shared arrays

---

lib/srfi-25.stk
tests/srfis/25.stk

Remember I told you there were some extra procedures that could be implemented, but I didn't?
So - I took almost all of the missing ones from the SRFI repository, and wrote some tests for them.
Only one is missing, because it does some weird things -- `share-array/prefix` uses an internal procedure of which even the SRFI author (Jussi Piitulainen) expressed his dislike ( in the comments).
I have included some documentation for these procedures.

Extra procedures with SRFI-25

---

lib/srfi-133/Makefile.am
lib/srfi-170/Makefile.am
lib/srfi-175/Makefile.am
lib/srfi-25/Makefile.am

I see you have split the mixed C/Scheme libs in different directories - that's nice, it will be more organized.
This PR adds some missing "\" at the end of the `Makefile.am` files in those subdirs. Without them the documentation is not generated, but the make process returns 0 anyway so it might not be obvious at first glance that it is happening:
```
make[3]: Entering directory '/home/jeronimo/pkg/scheme/STklos-github/lib/srfi-133'
../../src/stklos --no-init-file --case-sensitive -b ../../src/boot.img
f ../../doc/extract-doc srfi-133.c srfi-133.stk >> ../DOCDB
/bin/bash: line 1: f: command not found
make[3]: [Makefile:574: doc] Error 127 (ignored)
make[3]: Leaving directory '/home/jeronimo/pkg/scheme/STklos-github/lib/srfi-133'
make[3]: Entering directory …
```

Add missing line continuation in Makefiles

---

doc/skb/ffi.skb

I can't test if its rendered OK, but here is a small addition to the manual...

Describe behaviour of FFI on oversized numbers

---

src/number.c
tests/test-r7rs.stk

Currently STklos returns `#t` for `(finite? +nan.0)`, but R7RS says that
_"The finite? procedure returns #t on all real numbers except +inf.0, -inf.0, and +nan.0, ..."_
This PR changes `FINITE_REALP` so as to be R7RS compliant!

NaN flonums are not finite [ R7RS ]

---

utils/stklos-compile.stk

If the user asked for help, we don't need to exit with -1 status. The intended action (help) was performed successfully.

Don't exit with nonzero status for "-h" option

---

src/stklos.c

Fixes the main `stklos` command in the same way as #229 fixes other commands.

Fix stdout/stderr and exit code 0/1 in usage

---

SUPPORTED-SRFIS
lib/Makefile.am
lib/srfi-29.stk
lib/srfis.stk
tests/srfis/29.stk

One more.
This one has a small problem: Since it needs to change the `format` directives, I added a new `format` procedure, and shadowed the old one:
```
(define %stklos-format format)
(define-module SRFI-29
...
(define (%srfi-29:format A . rest)
);; END OF DEFINE-MODULE
(select-module STklos)
(import SRFI-29)
(define format (in-module SRFI-29 %srfi-29:format))
(provide "srfi-29")
```
But then tests seem to break in a way that's not easy to debug. If I change `format` to `%format`, in the SRFI andin the tests,then all tests pass:
```
(select-module STklos)
(import SRFI-29)
(define %format (in-module SRFI-29 %srfi-29:format))   ;; here, we don't override STklos format, just for testing
(provide "srfi-29")
```
I'm not sure why that happens.

Add SRFI-29: Localization

---

SUPPORTED-SRFIS
lib/Makefile.am
lib/srfi-94.stk
lib/srfis.stk
tests/srfis/94.stk

This SRFI changes the semantics of some standard Scheme functions, so
I had to save the old definitions and recover them back at the end of
the tests:
```
(define make-rectangular %make-rectangular)
(define make-polar %make-polar)
(define quotient %quotient)
(define remainder %remainder)
(define modulo %modulo)
```
Also... The procedures are of course slow. I am willing to reimplement them in C, but I'm not sure it would be a good idea to grow the C code so often. Maybe, if this is to be optimized/reimplemented in C, this SRFI could dynamically load a `.so` file?

Add SRFI-94 - Type-Restricted Numerical Functions

---

lib/object.stk

Add online documentation for these, so they'll be available on the online help.
Will do `define-method` later.

Add docs to define-class, find-class and is-a?

---

src/number.c

In number.c, NaNs would enter the tc_real case, and double2rational would then enter an infinite loop. This commit adds a guard for that.

Numerics: don't try to call double2rational on NaNs; use long to represent fixnums

---

lib/srfi-25/srfi-25.c
tests/srfis/25.stk

No big deal; there was a macro which was defined twice, and a variable that served no purpose.
Passes the tests.

Clean up bits of SRFI-25

---

src/proc.c

So, when compiler:generate-signature is true:
```
stklos> ((in-module STKLOS-COMPILER compiler:generate-signature) #t)
```
This would happen:
```
stklos> (define f (lambda (a b) (+ a b)))
stklos> f
#[closure f (a b)]        ;; fixed arity
stklos> (define g (lambda args (apply + args)))
stklos> g
#[closure g args]         ;; var arity
stklos> (define h (lambda (a b . c) c))
stklos> h
#[closure h (a b . c)]    ;; var arity II
stklos> abs
#[primitive abs]          ;; signature not available
```

Print signature with procedure object

---

lib/bonus.stk

`dotimes` uses `fx+`, but the documentation says the index is "an integer", and `dotimes` also uses `>=` later to check the exit condition, so I suppose it should be `+` instead of `fx+`.
If not, then I can make another PR changing `>=` to `fx>=?`, and changing the documentation.

Use + insted of fx+ in dotimes

---

src/print.c

@egallesio - is this the right fix for issue #96 ?
It seems to fix the crash, and passes all tests, but I'm not sure if there is some pretty-printing aspect that was lost with this patch.

printlist_star: don't access CDR if it's not a cons

---

SUPPORTED-SRFIS
lib/Makefile.am
lib/srfi-214.stk
lib/srfis.stk
tests/srfis/214.stk

This is SRFI-214, Flexvectors.
It depends on PR #258 because the implementation uses the `(let-values ((x ...`
way of using `let-values`.
About performance: access to individual vector elements is done via
`flexvector-ref` and `flexvector-set!`, and they only seem slower than
their `vector-*` counterparts because they check their arguments.
The rest of the SRFI rerference implementation, although could be
optimized, seems to not have any parts that are much slower than
native Scheme vectors, so we may leave it as it is for now.
Maybe we should remove the bounds check, which is done by the `vector-*`
procedures anyway? Or maybe not? :)

Add SRFI-214: Flexvectors

---

SUPPORTED-SRFIS
configure.ac
lib/Makefile.am
lib/srfi-132/Makefile.am
lib/srfi-132/srfi-132.c
lib/srfi-132/srfi-132.stk
lib/srfis.stk
tests/srfis/132.stk

Here's SRFI-132.
Some highlights:
* core of the SRFI (merging and sorting) written in C
* vector sorting uses [timsort](https://github.com/python/cpython/blob/main/Objects/listsort.txt)
- Seems more efficient than "quicksort reverting to insertion when n<16", for both random and totally ordered vectors (I have done some basic experiments)
* destructive list sorting uses almost no extra memory (only one tiny vector and a small stack);
Naive merge sort is too slow to be practical
* vector merging uses galloping (explained in the link about timsort above)
Remarks:
* `vector-stable-sort!` uses timsort , with most of the small optimizations.
* `list-stable-sort` runs `list->vector`, then `vector-stable-sort!`, then `vector->list`. Easy, and it's very fast.
* …

Add SRFI-132: Sort Libraries

---

SUPPORTED-SRFIS
lib/srfis.stk
tests/srfis/15.stk

Although withdrawn, it is supported and even used by the STklos compiler!
Some other implementations do support it also (Chez, Loko, Chicken, Iron)...
But I see you may not want to advertise it since it's been withdrawn.

Advertise SRFI-15 (fluid-let)

---

lib/Makefile.am
lib/srfi/214.stk
lib/srfi/Makefile.am

I have migrated one SRFI to the new R7RS `define-library` implementation. Tell me if this is OK, and I'll try to migrate others.

SRFI-214: change to R7RS library

---

lib/Makefile.am
lib/Makefile.in
lib/srfi/66.stk
lib/srfi/74.stk
lib/srfi/Makefile.am
lib/srfi/Makefile.in
src/Makefile.in

74 uses 66, so I converted both at once. Sorry, should have been two commits, but it's already done...

SRFIs 66 and 74: now R7RS libraries

---

etc/Docker/Dockerfile.latest
etc/Docker/Dockerfile.stable
etc/Docker/README.md

* Use same version of alpine for build and runtime.
This fixes a problem with libffi not being found.
* Update alpine to 3.15.
* Update STklos to 1.70 in the docs.
There seems to be a problem with the current image builder. See issue #309 (I opened the issue as well as the PR so people looking for "the issue with docker" may find it easily)
Fixes #309

Update and fix Docker image building

---

lib/Makefile.am
lib/Makefile.in
lib/srfi/113.stk
lib/srfi/128.stk
lib/srfi/Makefile.am
lib/srfi/Makefile.in
tests/srfis/113.stk

113 depends on 128, so both are migrated together.
113 still depends on SRFI-69, and uses a require instead of import. This would change when srfi-69 is migrated, I think

SRFIs 113 and 128 now are R7RS libraries

---

lib/describe.stk

The first commit is an enhanced describe for libraries and numbers
* R7RS libraries are described as R7RS libraries, with their
R7RS names  
* If we describe numbers as "rational number", "complex number", then
we should as well say "an integer number" instead of "an integer"...
Same for "real number".
* When a procedure is described, its signature is shown if available.
The second enables describe for ports. I have two questions, though:
* Shouldn't ports be objects of their own class? Currently they're not (a port is "`an instance of class <unknown>`").
* If a port is bound to a file, should we show the file name?
I can change the PR if necessary...

Describing things better :)

---

lib/Makefile.am
lib/Makefile.in
lib/srfi/70.stk
lib/srfi/Makefile.am
lib/srfi/Makefile.in

Ok - reexported all symbols mentioned in the SRFI, even those which were already available in R5RS / R7RS, so if the user changes them with `(define quotient *)`, for example, loading the SRFI will bring back the original one. This seems correct, since the intentin of the SRFI is to impose a certain semantics to the numeric fnuctions.

SRFI 70 -> R7RS library

---

src/env.c

GCC complained that 'not' was only being applied to the
left-hand side of an expression... Indeed, it was!
This commit fixes it.

Fix boolean operator precedence warning

---

src/fixnum.c
src/stklos.h

I'm not sure about this one. It would maybe make fixnum operations a bit faster, but also makes the code a little less readable.
Also, the optimizations in `fxodd?` and `fxeven?` look a bit like something that "a smart compiler would figure out anyway"...
But I didn't check the generated assembly for them. And I didn't run any benchmarks this time either... 
Commit message:
Try to avoid tagging/untagging in some places.
A new macro, `UNTAG`, was created that just clears the two first bits of a word.

Some fixnum optimizations

---

lib/stklos/itrie.c
src/fixnum.c

The bit-counting code that uses a lookup table was duplicated
(in `fixnum.c` and `itrie.c`). This commit makes `itrie` use the
version in `finum.c`
- Changed `bit_count` in `fixnum.c` from `static` to `extern`
- Made `itrie.c` use it
@egallesio is this ok?
I think it would not be a good idea to make itrie use the Scheme primitive, since all itrie internal functions are optimized to use native long integers, and using the Scheme primitive would require boxing-then-unboxing.

Don't duplicate lookup table

---

src/stklos.h
src/vm.c

Not for everything in STklos -- using `long` is good, since
it makes STklos use the ideal integer size for integer arithmetic
depending on the platform. But the VM will now always use exactly
two bytes for opcodes, so we can be sure that the bytecode will
always be portable.
```
short          -> int16_t
unsigned short -> uint16_t
```
One thing: when compiling SRFI 25, gcc complains that we're converting `int` into `int16_t`, producing overflows:
```
25-incl.c:104:1: warning: overflow in conversion from ‘int’ to ‘short int’ changes value from ‘65535’ to ‘-1’ [-Woverflow]
104 | 0xffff,  0x25,  0x75, 0x100,  0x25,  0x65,  0x56,  0x3f,   0x1,  0x6e,
| ^~~~~~
25-incl.c:109:15: warning: overflow in conversion from ‘int’ to ‘short int’ changes value from ‘65532’ to ‘-4’ [-Woverflow]
109 | …
```

Use fixed-size integers for opcodes

---

SUPPORTED-SRFIS
lib/Makefile.am
lib/srfi-221.stk
lib/srfis.stk
tests/srfis/221.stk

SRFI-221 was finalized today, so I ported it.
However, something isn't working, I can't tell why:
SRFi-221 uses SRFI-41. So this is in thebeginning of srfi-221.stk:
```
(require "srfi-41")
(require "srfi-158")
(define-module SRFI-221
(import SRFI-41)
(import SRFI-158)
(export
accumulate-generated-values
genumerate
gcompose-right
gcompose-left
gchoice
generator->stream
stream->generator)
```
But then,
```
stklos> (require "srfi-221")
"srfi-221"
stklos> (define g-expect (circular-generator 1 2 3))
;; g-expect
stklos> (define g-actual (stream->generator (stream-constant 1 2 3)))
;; g-actual
stklos> (generator->list (gtake g-expect 20))
(1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2)
stklos> (generator->list (gtake g-actual 20))
**** Error:
g-actual: variable `stream-null?' …
```

Add SRFI-221: Generator/accumulator sub-library

---

extensions/Makefile.am
lib/srfi/144.c
utils/shlib-options

This PR brings three modifications to support OpenBSD:
* In `extensions/Makefile.am`, 'make' was hardcoded, and this fails when the name of GNU Make is `gmake` such as in BSD systems.
* Adds OpenBSD  to `utils/shlib-options`
* Calculate `DBL_TRUE_MIN` when necessary
Fixes #374 and fixes #375 .

OpenBSD support: Use $(MAKE) instead of 'make'; include OpenBSD in utils/shlib-options

---

lib/stklos/Makefile.am
lib/stklos/readline-complete.c
lib/stklos/readline-complete.stk

I added simple tab completion to the STklos REPL -- but I think it still needs some work.
To use:
```scheme
(import (stklos readline-complete))
(init-readline-completion-function)
```
and try to hit tab after a partially-written symbol name.  Readline will bring several options to complete the word (the symbols extracted from the STklos module and the current module).
By default, **exported** symbols in the STklos module and **any** symbols in the current module are searched for completions. This behavior can be changed by changing the parameter `readline-complete-get-modules`.
Questions:
* There is a global `gen` variable in the C file that holds the Scheme procedure/generator that produces matches. I'm not sure what would be the best thing to do with it (make it …

Add tab completion to readline

---

SUPPORTED-SRFIS
lib/srfi/130.stk
lib/srfi/152.stk
lib/srfi/Makefile.am
lib/srfis.stk

One more SRFI :smiley: 
* The implementation of SRFI 130 had to be adjusted.
SRFI 130 impoted and redefined some identifiers from SRFI
13, and that caused SRFI 152 to fail to re-redefine them
(can't tell why, but it's not a good idea to redefine an
imported symbol anyway).
* string comparison functions are redefined so they will accept
zero arguments: (string=?) is legal and retruns #t

Add SRFI 152: String Library (reduced)

---

lib/compiler.stk
tests/test-misc.stk

I think the `void` procedure could be inlined.  Is there some reason for not doing it?
This is what STklos does, currently:
```
stklos> (disassemble-expr '(void))
000:  PREPARE-CALL
001:  GREF-INVOKE          0 0
004:
stklos> (disassemble-expr '(void 1 2))
000:  PREPARE-CALL
001:  ONE-PUSH
002:  INT-PUSH             2
004:  GREF-INVOKE          0 2
007:
```
After this patch -- not only we have less instructions, but we also avoid a procedure call.
```
stklos> (disassemble-expr '(void))
000:  IM-VOID
001:
stklos> (disassemble-expr '(void 1 2))
000:  IM-ONE
001:  SMALL-INT            2
003:  IM-VOID
004:
```
Which is the same as if we had no procedure call, and just either
used `#void` or `(begin  [args]  (void))` directly:
```
stklos> (disassemble-expr '#void)
000:  IM-VOID …
```

Optimize (void ...)

---

lib/readline-complete.c

`readline-complete.c` needs to use `malloc` instead of `libgc`, and I forgot to check for `NULL` when I wrote it.

Check for NULL from malloc

---

lib/stklos/itrie.c

Make the accessor macro work on the shorter variant of the struct, so GCC-12 will be happy.

Silence a GCC warning

---

src/uvector.c

A typo: the code was allocating room for `vector_obj`, and not `uvector_obj`. :)

Fix allocation of uvectors

---

src/vm.c

A small fix to `STk_values2vector` (which is used in SRFI 25, and in the -- almost ready -- implementation of SRFI 160).
For example, suppose if we write, in C, a procedure similar to `map` or `fold`, which iterates through a structure, applying a procedure KONS (or PROC).
Also suppose PROC takes 2 arguments _**and produces 2 values**_.
In C, we'd do
```c
STk_values2vector ( STk_C_apply(PROC, 2, a, b),  res );
```
However, if later the user passed a procedure that produces the wrong quantity of values, then `STkvalues2vector` (as it is now) would signal an error with a cryptic message, _"bad vector"_.
(Indeed, it's a vector of the wrong size, which was passed to hold the values -- but the Scheme programmer may not even know
that this is how things are implemented …

Enhance error message in STk_values2vector

---

lib/recette.stk

Commit 4f41e8b55e784c4f740c7db09b3d33677a970e58 changed this file, and included an extra closing parens, actually closing 
the module definition earlier than what it was done before. This patch reverts that.

Remove extraneous parenthesis

---

lib/srfi/25.c

Otherwise, a primitive won't be allowed in share-array (even
though this is unlikely because of the requirements of share-array,
it could be done).

SRFI-25: use STk_procedurep instead of CLOSUREP

---

etc/completion/stklos

The file `etc/completion/stklos` is a bash script that registers a completion function for the `stklos` command in Bash. 
Source this file to get tab completion for the STklos command in Bash.  For a permanent effect, either source this from your
`.bash_profile` or put it with the other bash completion files in your system -- for example, in Debian and Debian-based systems, this will be `/usr/share/bash-completion/completions/`

Add bash tab completion to STklos

---

lib/assembler.stk

After the changes made to the compiler to accomodate the new macros, `disassemble-expr` stopped working:
```
(disassemble-expr '(+ 2 x))
**** Error:
%fast-struct-ref: bad structure `()' in `scope-locals'
```
because the null environment is now represented by `#f`, and not `'()`, so the call to `compile` in `assembler.stk` should be adjusted.

Fix `disassemble-expr`

---

lib/srfi/133.c
lib/srfi/133.stk
tests/srfis/133.stk

While working on some other SRFIs, I've found two problems with my implementation of SRFI 133. This PR fixes both.
When an exported symbol is already defined in STklos, we
actually define it inside the module, as in
```
(define vector-fill! (symbol-value 'vector-fill! scheme))
```
because otherwise SRFI-133 would require the SCHEME (or STklos)
module in order to work. Also, if someone changed the binding of
vector-fill!, for example, in module STklos, and SRFI-133 counts on
its original binding, then SRFI-133 will not behave as intended.
R7RS specifies that, for vector-copy!,
> _"The order in which elements are copied is unspecified, except that if
>  the source and destination overlap, copying takes place as if the
>  source is first copied into a temporary vector and …

Fixes two issues with SRFI 133

---

src/number.c

Hello!
The functions `STk_integer2int32` and `STk_integer2uint32` determine if a number fits 32 bits as this:
For `int32`:
```c
if ((- INT32_MAX - 1) <= val && val < INT32_MAX)
```
For `uint32`:
```c
if (val < UINT32_MAX)
```
However, the constants `INT32_MAX` and `UINT32_MAX` are not the power of two (that would not fit into the number), they are the actual largest representable number. So both comparisons can be changed from `<` to `<=`, and we get one more  epresentable number in each.
Not really a big deal. However, the tests for SRFI 160, for example, check if the largest 32-bit number fits a 32-bit uniform vector, and they'll fail with the current implementation.
This patch changes both comparisons into `<=`.

Fix off-by-one issue in conversion to 32 bits

---

src/utf8.c
tests/test-utf8.stk

When the first byte is $>=$ `0xf0`, the algorithm was decoding incorrectly:
```scheme
(list->string (list (integer->char 65537)))
=> "𐀁"        ;; Ok
(string->list (list->string (list (integer->char 65537))))
=> (#\Ё)      ;; Oops! list->string and string->list
;; do not work as inverses, because the
;; character is decoded incorrectly in
;; string->list (and string-ref too)
```
This fixes the problem. Also included some tests: the full Unicode range (excluding surrogates) is verified to encode and decode correctly, as per
```scheme
(equal? (string->list (list->string (list (integer->char i))))
(list (integer->char i)))
```

Fix small glitch in `STk_utf8_grab_char`

---

src/number.c

When one calls
`(make-polar 1 2+1i)`
or
`(make-rectangular 2+1i 3)`
STklos says `2+1i is a bad number` - which is not very clear.
A better error message here would be
`2+1i is not a real number`,
which we adjust here (a function that prints this error message already exists, but wasn't being used in these procedures).
This patch preserves the "bad number" message when an argument really isn't a number:
```
stklos> (make-rectangular "x" 2)
**** Error:
make-rectangular: `"x"' is a bad number
```

Fix error message in `make-{polar,rectangular}`

---

.editorconfig
doc/hacking/hacking.adoc

Just mentioning `.editorconfig` in `hacking.adoc`.
By the way, the file has a generic
```
indent_size              = 4
```
and a specific
```
[*.{c,h}]
tab_width = 2
```
But the last one only changes the width of the tab character. Shouldn't it have been `indent_size = 2`?

Mention editorconfig in hacking.adoc, and use indent_size for indentation size

---

SUPPORTED-SRFIS
configure
configure.ac
lib/srfi/160.stk
lib/srfi/160/Makefile.am
lib/srfi/160/Makefile.in
lib/srfi/160/base.c
lib/srfi/160/base.stk
lib/srfi/160/tagvector-template.stk
lib/srfi/4.stk
lib/srfi/Makefile.am
lib/srfis.stk
src/read.c
src/stklos.h
src/uvector.c
tests/srfis/160.stk

Here's R7RS Large's  SRFI-160,  Homogeneous numeric vector libraries
This one was quite an adventure...
* This SRFI has sublibraries, so for the first time we have autotools descending into a subdir of `lib/srfi`.
* Several sublibraries are almost identical, so we generate them from a template. Using `sed` (!) in the `Makefile`.
* A relatively small C core can perform a large amount of operations that are described in the SRFI.
* Exports in the convenience module `srfi/160` are done programatically, and not using `export`.
Adds SRFI-160, which extends SRFI 4, bringing ideas from SRFIs 152 and 133.
The SRFI requires the creation of the libraries:
- `(srfi 160 base)`,  with basic procedures
- `(srfi 160 s8)`,
`(srfi 160 u8)`,
`(srfi 160 s16)`,
...,
`(srfi 160 c128)`,
with …

Add SRFI-160: Homogeneous numeric vector libraries

---

SUPPORTED-SRFIS
lib/srfi/125.stk
lib/srfi/Makefile.am
lib/srfi/Makefile.in
lib/srfis.stk
src/hash.c
tests/srfis/125.stk

Here's R7RS large hashtables... There are still some issues, and it actually needs immutable hashtables (PR #383 ).
- This implmentation directly uses STklos' hashtable API (and doesn't even load SRFI 69)
- In srfis.stk, the alias given is the one defined for it in R7RS/Large Tangerine Edition ("hash-table"). But this doesn't (yet) make it possible to do (import (scheme hash-table)). Maybe later.
Not perfect yet:
- ~SRFI 125 requires immutable hashtbles, which STklos doesn't yet have;~ we have those now :)
- Maybe ~`hash-table-clear!`~ and `hash-table-empty-copy` could be implemented as primitives? They do excessive work because there's no way to remove all data in a hash table. But would it be OK to implement them in core, or d owe create a C sublibrary just for them? …

Add SRFI-125: Intermediate Hash Tables

---

tests/do-test.stk
tests/test-hash.stk

The hash tables are already tested with the tests for SRFI 69, but I though it would be interesting to test them without the changes introduced by the SRFI.

Add tests for hash tables

---

SUPPORTED-SRFIS
doc/Makefile.in
lib/srfi/233.stk
lib/srfi/Makefile.am
lib/srfi/Makefile.in
lib/srfis.stk
src/Makefile.in
tests/srfis/233.stk

Hi @egallesio ! I'm not dead either! :)
This PR adds SRFI 233 (INI files) to STklos. The module `(srfi 233)` exports two procedures,
```
make-ini-file-generator
make-ini-file-accumulator
```
which can be used to read and write traditional `.ini` files.
A very simple SRFI, easy to implement.

Add SRFI-233: INI files

---

SUPPORTED-SRFIS
lib/scheme/comparator.stk
lib/srfi/128.stk
lib/srfis.stk
tests/srfis/162.stk

Here's SRFi-162, because I thought we could have one more, and this one was easy...
As per suggestion in the SRFI text, I have not created a new file, but included this in the previous comparator library, `srfi-128.stk` so
* `srfis.stk` says you need to load `srfi-128.stk` in order to get SRFI-162;
* `srfi-128.stk` provides both libraries
Passes all tests.

Add SRFI-162: Comparators sublibrary

---

SUPPORTED-SRFIS
doc/HTML/stklos-ref.html
lib/srfi/236.stk
lib/srfi/Makefile.am
lib/srfi/Makefile.in
lib/srfis.stk
tests/srfis/236.stk

SRFI 236 went final, and since it's trivial, I've decided to make this PR. :)
The implementation I've included is different (and simpler) from the reference implementation: it just wraps the expressions in `begin`, but appending `(void)` as last expression.

Add SRFI 236 - Evaluating expressions in an unspecified order

---

lib/scheme/Makefile.am
lib/scheme/Makefile.in
lib/scheme/bytevector.c
lib/scheme/bytevector.stk
tests/do-test.stk
tests/lib/scheme/bytevector.stk
tests/test-libs.stk

These are the same as R6RS-bytevectors, which were chosen as part of R7RS-Large.
* As much as possible, operations are performed in C for performance (even the trivial `bytevector=?` was written in C).
* A known issue is that this introduces an incompatibility with R7RS (in `vector-copy!`), but since it's in a library, one can always rename when importing (which seems to be the consensus solution).
* Since this is not a SRFI, it includes the library in the `scheme` subdirectory (is this OK?)
~This depends on PR #414~ (that PR was already accepted)

Add R7RS-Large bytevectors

---

SUPPORTED-SRFIS
lib/srfi/43.stk
lib/srfi/Makefile.am
lib/srfi/Makefile.in
lib/srfis.stk
tests/srfis/43.stk

This SRFI was being considered to inclusion in R7RS large when it was found that it was actually incompatible with R7RS small. Then SRFI 133 was designed, but it did not officially supersede SRFI 43.
I thought it would be interesting to have this one, just in case someone wants it (for running old code, for example).
Since there are only 6 incompatible procedures, and it's easy to rename symbols when importing and exporting R7RS libraries, there is no harm in having SRFI 43 available also.
(This one is available in Gauche, Gerbil, Guile, Larceny, Sagittarius and perhaps others)
This implementation:
* Takes as many procedures as possible from the `SCHEME` module;
* Takes others from SRFI-133;
* And finally, provides code for the 6 incompatible procedures, `vector-map`, `vector-map!`, …

Add SRFI 43 - Vector Library

---

.gitattributes

The .stk file extension is not recognized by GitHub Linguist, the system used to syntax-highlight and analyze files on GitHub. Many files are detected as Scheme through text analysis but [some](https://github.com/egallesio/STklos/blob/master/lib/load.stk) are not, and are displayed as plain text.
This makes GitHub detect them as Scheme and properly highlight them. This should also allow for syntax highlighting in pull requests.

Create .gitattributes file so .stk files are Scheme-highlighted

---

utils/stklos-config.in

Hi @egallesio - I'm not sure this is what you indended (was it a typo/thinko? `LIB_SUMMARY` <-> `CONF_SUMMARY`?)
Could this be a resolution to #379 ?
Seems to work now, I'm not sure it's the exact output you wanted:
```
$ stklos-config -L
(:system (libffi libpcre libgmp libgc ) :compiled () :configure ( "CC=gcc" "CFLAGS=-g -O2"))
```

Fix variable name in stklos-config.in

---

lib/srfi/215.stk
tests/srfis/215.stk

Make the error messages more like the STklos style, and add two tests for errors.
Also test for integer before testing for exact, otherwise in case a bad number is given, the `exact?` procedure will complain that `x is not a number`, and the user won't see that the error was triggered in SRFI-215.

Better error messages for SRFI-215

---

.github/workflows/ccpp.yml
lib/Makefile.am
lib/Makefile.in

`update-srfi-list.stk` uses the procedure `parse-arguments`, which is defined in `getopt.stk`.  But the Makefile dependencies were not reflecting that.
Fixes #427 
update: included a commit from @amirouche

Add missing Makefile dependencies

---

lib/compiler.stk

The ones without question mark at the end were not optimized:
```
stklos> (disassemble-expr '(fx< 1 a))
000:  PREPARE-CALL
001:  ONE-PUSH
002:  GLOBAL-REF-PUSH      0
004:  GREF-INVOKE          1 2
007:
stklos> (disassemble-expr '(fx<? 1 a))
000:  ONE-PUSH
001:  GLOBAL-REF           0
003:  IN-FXLT
004:
```
With this PR, bothe produce the same output (without the procedure call).
The speed difference can be quite large.
Out of curiosity, I timed two code chinks, compiling STklos with both `-O2` and with `-O0`:
```scheme
(define a 10)
(time
(repeat 1_000_000_000
(fx<? 1 a)))   ;; with -O2: 44835.161 ms
;; with -O0: 77795.824 ms
(time
(repeat 1_000_000_000
(fx<  1 a)))   ;; with -O2: 60694.25 ms
;; with -O0: 117426.244 ms
```
So, from 44.8s to 60.9s in an usual (optimized) setting.
That …

Inline `fx=` `fx<` and similar

---

lib/srfi/19.stk
lib/time.stk
tests/srfis/19.stk

- The `copy-time` procedure would call `make-time` with parameters `#f #f #f`, but the `make-time` procedure only accepts proper integers for second and nanosecond
- `time-monotonic->date` should do the same as `time-tai->date`, but was not, so the results were wrong
- We now check the arguments to `make-date` (`make-time` already did this).
Added tests for several more cases.

Fixes to SRFI-19

---

SUPPORTED-SRFIS
lib/srfis.stk

It's `define-values`, which is part of R7RS; the SRFI is intended for R6RS systems. But since R7RS systems do support it out of the box, advertising it would seem the right thing to do.

Declare support for SRFI 244

---

lib/bonus.stk
tests/test-misc.stk

For completeness. We have `null?`, `eof-object?`, `zero?`, and other procedures that are essentially convenience for
`(lambda (x) (eq? x some-special-object))`, so why not this one also?
This would be similar, I think, to the `unspecified?` procedure in MIT Scheme.

Add `void?`

---

src/number.c
tests/srfis/94.stk
tests/test-number.stk

2+3 is not the same as 2. It's not even a number...
Fixes #461
(Is it ok to just do `STk_error("bad number %s", str)`?   Is `str` always zero-terminated?
All tests pass, and now the wrong "numbers" are not read as numbers anymore:
```
stklos> #xa+bi
10+11i
stklos> #xa+b
**** Error:
%read: bad number a+b
stklos> #b1+1
**** Error:
%read: bad number 1+1
stklos> #b1+1i
1+1i
stklos> 2+3
**** Error:
%read: bad number 2+3
stklos> 2+3i
2+3i
stklos> (string->number "#b10_1-111111")
**** Error:
string->number: bad number 101
stklos> (string->number "4+5")
**** Error:
string->number: bad number 4+5
stklos> (string->number …
```

Fix misreading of numbers

---

src/number.c
tests/test-number.stk

Specifically for `(atanh 1)` and `(atanh -1)` we trigger an error, as in Chez, Gambit and most Common Lisp implementations (as opposed to doing math with infinities).
Also included some (very few) tests.
A survey of which Schemes support these functions is available here: https://github.com/schemedoc/surveys/blob/master/surveys/hyperbolic-trigonometric.md
* I changed the placement of `#define transcendental(name)` to make things clearer (the hyperbolic trigs are defined after several others)
In general, `(asinh (sinh x))` and similar compositions should be equal to x, except for inexactness due to the internal floating point number approximation for real numbers.
```scheme
(sinh (asinh 0+1i)) => 0.0+1.0i
(cosh (acosh 0+1i)) => 8.65956056235493e-17+1.0i
(tanh (atanh 0+1i)) => 0.0+1.0i
``` …

Add hyperbolic trigonometric functions

---

src/number.c

The problem is that `-INT_VAL(x)` is not a fixnum when `x` is `fx-least`, but the C code was assuming it was.
Fix #470

Fix `(abs fx-least)` being negative

---

src/number.c
tests/test-number.stk

If at least one of the arguments is a bignum, call the GMP.
This brings a really nice speedup to gcd *and* to lcm (which uses gcd internally):
1. GCD bignum x bignum   4.960 -> 0.175
2. LCM bignum x bignum   4.771 -> 0.330
3. GCD bignum x fixnum   7.490 -> 2.106
4. LCM bignum x fixnum  11.648 -> 6.681
(Times in seconds)
1: calculate GCD of two bignums 100_000 times
2: calculate LCM of the same two bignums from (1), 100_000 times
3: calculate GCD of a bignum and a fixnum 10_000_000 times
4: calculate LCM of the same two numbers from (3), 10_000_000 times
Each benchmark was repeated 20 times.
**CAVEAT**: I did not test with different numbers, and this *may* make a difference (the GCD can be calculated quicker, depending on its arguments).
**EDIT**: this also fixes a problem I've seen:
``` …
```

Use GMP for bignum GCD (results in a really good speedup)

---

configure
configure.ac

Your configure test "See in what direction the stack grows (code stolen from Sawfish)" fails to work correctly with the version of clang that comes with Xcode 12 and later on macOS (and any other compiler if you have `-Werror=implicit-function-declaration` in CFLAGS) because you use the `exit` function but haven't included the header where it is defined:
```
configure:7228: /usr/bin/clang -o conftest -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 conftest.c -lpthread  >&5
conftest.c:83:37: error: implicitly declaring library function …
```

Don't implicitly declare exit in configure check

---

src/list.c
src/number.c

This would make the messages more coherent, and would also make it easier to maintain those messages.
By the way, @egallesio -- what about having those in a specific file?
It would be nice to have a file `error-functions.c`   (with the commonly used error-reporting functions, like "bad list", "bad integer" and so on), and their prototypes in `error-functions.h`. If you say it's OK I can do that.
(Some very specific error messages would still use `STk_error` of course...)

Use error specialized functions instead of `STk_error()`

---

lib/describe.stk
lib/help.stk

In `help.stk` and `describe.stk`
Also describe closures and primitives separately in `describe.stk`.
And don't try to call `procedure-signature` on primitives...
Some examples:
```
stklos> (describe +)
#[primitive +] is a primitive procedure.
stklos> (define (f a b) (+ a b))
;; f
stklos> (compiler:keep-source #t)
stklos> (define (g a b) (- a b))
;; g
stklos> (compiler:keep-formals #t)
stklos> (define (h a b) (/ a b))
;; h
stklos> (compiler:keep-source #f)
stklos> (define (i a b) (* a b))
;; i
stklos> (describe f)
#[closure f] is a procedure.
stklos> (describe g)          ;; keep-source also keep formals:
#[closure g (a b)] is a procedure.
The source code is available -- call `procedure-source` on it
stklos> (describe h)
#[closure h (a b)] is a procedure.
The source code is available -- …
```

Change `%procedure-signature` to `procedure-formals`, describe closures and primitives better, and also describe bytevectors

---

src/fport.c
src/fport.h

I noticed a typo in the license header of fport.c and while reading through the file I made some other fairly nitpicky changes that I hope you don't mind too much.

Fix typos and wording in fport.c and fport.h

---

configure
configure.ac

This fixes the configure summary so that it doesn't identify most Darwin versions by the nickname "DARWIN_OLD" which was strange to see on current OS versions. Previously the only Darwin versions not identified as "OLD" were 9, 10, and 11, even though they were released over 15, 13, and 11 years ago, respectively. Whereas before the summary on my system would show:
```
SUMMARY
*******
System:  Darwin-21.4.0
OS nick:  DARWIN_OLD
```
it now shows:
```
SUMMARY
*******
System:  Darwin-21.4.0
OS nick:  DARWIN_21
```
I realize this changes the preprocessor macros. Previously a macro called `DARWIN_OLD` would have been defined. But I don't see anywhere in the code that made use of that macro.

Identify all Darwin OS versions

---

QUICK-INSTALL.md

The markdown does not render properly when the backticks are at the wrong indentation.

Fix formatting problems

---

doc/stklos.1.in

See 86b6c11c where the same sentence was removed from the README.

Remove sentence about STklos library from manpage

---

lib/bonus.stk
lib/load.stk
lib/r7rs.stk
lib/regexp.stk

Some procedure are defined inside closures using `set!`. Some of them did not have their names set, and this patch does that.
The procedures are:
`base64-encode-string`, `base64-decode-string`, `ansi-color-protect`, `require/provide`, `provide`, `provided?`, `try-load`, `equal?`.
Also, `ansi-color` had the name of `do-color`.

Set some procedure names

---

lib/scheme/bytevector.c

Some (six) tests were failing on Android because we were trusting that the sign of `char` would be the same everywhere...  So in Android, `bytevector-sint-ref` was not returning signed integers, as well as `bytevector-s8-ref`.
Changed several occurrences of `char` to `int8_t`. Passes all tests:
- x86_64 GCC
- x86_64 Clang
- Android Clang (which was failing!)
(@egallesio - sorry the buggy code was mine... I should have been more careful.)

Fix bytevector portability (failing tests on Android)

---

src/number.c

There doesn't seem to be any difference in using this or not -- all tests pass and the average performance seems the same in both cases.

Don't define `__NO_MATH_INLINES`

---

src/env.c
src/vm.c

If this useful? :)
* In `env.c`, move the error functions to after the declaration of the module structure, so we can use `MODULE_NAME` in `error_unbound_variable`
* Change `error_unbound_variable` so it takes the module as argument  instead of the module name -- so it can decide wether to report  an unbound variable in "module x" or "library x"
* Use `error_unbound_variable` everywhere
* Change the VM in a similar way (`error_unbound_variable` will take a module as second argument and include its name in the error message).
```
stklos> a
**** Error:
%execute: variable `a' unbound in module `stklos'
stklos> (define-library empty)
;; empty
stklos> (in-module empty x)
**** Error:
symbol-value*: variable `x' unbound in library `empty'
stklos> (select-module STKLOS-COMPILER) …
```

Report module or library name for unbounded variables

---

lib/help.stk

Don't use `major.minor.PATCH` for looking up the database; it's just `major.minor` (`short-path`).
Otherwise, we get this:
```
stklos> (help memq)
Warning: cannot open "/usr/local/share/stklos/1.70.1153/DOCDB".
```

Fix help docs path

---

utils/shlib-options

Use the two-level namespace for loadable modules on macOS instead of the flat namespace. The flat namespace is a relic from Mac OS X 10.0 (2001). The two-level namespace was introduced in Mac OS X 10.1 (2001) and the ability to resolve undefined symbols at runtime in the two-level namespace was added in Mac OS X 10.3 (2003). There's no reason to use the flat namespace anymore today.
For more info about the differences between the two types of namespaces and why the two-level namespace is better:
https://web.archive.org/web/20030604123710/http://developer.apple.com/techpubs/macosx/ReleaseNotes/TwoLevelNamespaces.html
I'm linking to an archived copy of that page because Apple has removed it from their site or at least moved it somewhere I could not find it, and it is outdated. For example …

Use two-level namespace for bundles on macOS

---

src/number.c
tests/srfis/70.stk
tests/test-number.stk

The following condition in the primitive definition for `expt`:
```c
if (negativep(y))
return div2(MAKE_INT(1),
my_expt(x, sub2(MAKE_INT(0), y)));
```
was preventing it from working with complex exponents, because `negativep` will trigger an error for complexes. Adding `!COMPLEXP(y)` fixes it.
However, there is another issue that we also fix with this PR: R7RS says that
> "The value of $0^z$ is $1$ if `(zero? z)`, $0$ if `(real-part z)` is positive, and an error otherwise.  Similarly for $0.0^z$, with inexact results."
But the current code would not do the "zero when (real-part z) is positive", so we also fix this in `my_expt`.
Then, we add some tests. And adjust one test from SRFI 70:
```scheme
(test "expr.4" 1    (expt (sqrt 3) 0))
```
This won't work with R7RS, because `(sqrt 3)` is …

Make `expt` work with complex exponents, and adjust to one R7RS requirement

---

lib/bonus.stk
lib/compflags.stk
lib/compiler.stk
tests/test-misc.stk

`dotimes` creates a `LET` even when not necessary:
```scheme
(macro-expand '(dotimes (i 10) 'work))
=> (let ((G1 10))
(do ((i 0 (+ i 1)))
((>= i G1)
(void))
'work))
```
The new variable `G1` is not necessary -- since 10 is constant, it could have been used in the body instead of `G1`, and the `LET` is superfluous. For nested `dotimes`, this can make a difference.
With this patch we check (at macro expansion time) if `count` is a number, and when it is, we generate a begin instead of a let.
For example:
```scheme
(macro-expand '(dotimes (i MAX) 'work))
=> (let ((G77 MAX)) (do ((i 0 (+ i 1))) ((>= i G77) (void)) 'work))
(macro-expand '(dotimes (i 10) 'work))
=> (begin (do ((i 0 (fx+ i 1))) ((fx>= i 10) (void)) 'work))
```
The second case will be faster for nested `DOTIME`s, because it …

Optimize `dotimes`, `repeat`, `while` and `until`, and also do some loop unrolling in `repeat`

---

src/signal.c
src/system.c

- Sort in alphabetical order.
- EAGAIN and EDEADLK were listed twice.
- The following entry was incorrect:
#ifdef ENOTSUP
CODESET_ERRNO(EOPNOTSUPP)
#endif
- Note: EOPNOTSUPP and ENOTSUP are sometimes the same number, sometimes different. We should list both names.

Clean up STk_errno_names

---

src/number.c
tests/test-number.stk

R7RS requires that
```scheme
(log  0.0) => -inf.0
(log -0.0) => -inf.0+(PI)i
```
STklos was returning `-inf.0` for both cases. This patch corrects that.

Compute (log -0.0) as per R7RS

---

src/number.c
tests/test-number.stk

If the exponent is a floating point number that happens to represent an integer precisely (that is, with fractinal part equal to exactly zero), turn it into exact, perform the operation, then turn it back into inexact.
Before this patch:
```scheme
stklos> (real-precision 50)
stklos> (expt 2 3.0)
7.9999999999999982236431605997495353221893310546875
stklos> (exact (expt 2 3.0))
4503599627370495/562949953421312
```
After this patch:
```scheme
stklos> (real-precision 50)
stklos> (expt 2 3.0)
8.0
stklos> (exact (expt 2 3.0))
8
```

Make `expt` more precise

---

lib/scheme/bytevector.c

I've found two bugs in the `(scheme bytevector)` library.
I have noticed that the `test/error` macro in `tests/test.stk` doesn't actually do anything: it ignores errors, but doesn't complain when **no** error is produced!   So I fixed it (will include in a later PR), and... Found several problems.
This is one of them -- now the test suite complains that we didn't error when the wrong index (non-aligned) was used. 
Later I'll send a PR with a new test macro, and several fixes in SRFIs, in the core, and in tests.
Otherwise STklos crashes!
Also, convert all numbers to imprecise (except complexes) before storing them in the bytevector (only complexes can't be turned into reals -- for bignums, if they don't fit a double, we store an infinity; for rationals, if they're too small, they become …

Fix crash in `(scheme bytevector)`, and adjust the procedures to the spec.

---

src/number.c

```
stklos> (gcd 10 'a)
0
stklos> (gcd 'a 10)
**** Error:
gcd: exact or inexact integer required, got a
```
Oh, that is because:
```c
if (STk_integerp(n1) == STk_false) error_not_an_integer(n1);
if (STk_integerp(n1) == STk_false) error_not_an_integer(n2);
^^
^^
```
Oops.. Fixed!

Fix typo in `gcd2` which was allowing arbitrary types (not just integer numbers) as arguments. (One-liner)

---

extensions/gtklos/README.md

As a mac user I was positively surprised that I was able to build the examples in the extensions/gtk folder. Maybe these notes make it bit easier for the next user.

some notes on the gtk requirement

---

src/number.c
tests/test-number.stk

In `exact_exponent_expt`, some calls were missing, and STklos would crash on this, for example:
```scheme
(expt (expt 2 100) -2)
```
This patch also includes a test for that.
If an exponent is reeealy too large:
```scheme
(expt fx-greatest 100000)
```
STklos will report a `SIGABRT` from the GMP.
Anyway, when the exponent is too large, several Scheme implementations either crash (Chez, Guile, Sagittarius), or report an error like "our of memory" or "exponent too large" (Gosh, MIT). Kawa and Bigloo return an imprecise infinity -- so the behavior of STklos should be OK.
* Use `mpz_ui_pow_ui` instead of creating and setting the value of a new mpz number to then call `mpz_pow_ui`.
Since that function only accpets *unsigned* integers, we check the sign, pass the number as unsigned, then if the …

Better use of GMP in `expt` (fixes crash)

---

src/number.c
tests/test-number.stk

```
stklos>  (expt -2.0 0.5)
-nan.0
stklos>  (expt -2.0 1/2)
8.65956056235493e-17+1.41421356237309i
```
Oops. This was my recent PR.
We should not call `pow` for negative base and inexact exponent.

Make `expt` work again for inexact exponent + negative base

---

lib/compiler.stk

Currently STklos has all `cxr` aliases implemented as procedures:
```scheme
(disassemble-expr '(caddar x) #t)
000:  PREPARE-CALL
001:  GLOBAL-REF-PUSH      0
003:  GREF-INVOKE          1 1
006:
Constants:
0: x
1: caddar
```
This patch optimizes this, opening their code:
```scheme
(disassemble-expr '(caddar x) #t)
000:  GLOBAL-REF           0
002:  IN-CAR
003:  IN-CDR
004:  IN-CDR
005:  IN-CAR
006:
Constants:
0: x
```
Some timings:
```scheme
(let ((a #f) (L '(a b c d e f g))) (time (repeat 50_000_000 (set! a (cadddr L)))) a)
before patch: 4174.988 ms
after patch:  2786.303 ms
```
```scheme
(let ((a #f) (L '(a b c d e f g))) (time (repeat 50_000_000 (set! a (cadr L)))) a)
before patch: 3703.763 ms
after patch:  2479.088 ms
```
```scheme
(let ((a #f) (L '((((a))) b c d e f g))) (time (repeat …
```

Optimize (inline) the `c_r` aliases to compositions of `car` and `cdr`

---

lib/scheme/Makefile.am
lib/scheme/list.c
lib/scheme/list.stk

Last one today, I promise :)
There are three commits in this PR:
The reference implementation of SRFI-1 recommends that the following procedures be inlined:
```
%cars+, %cdrs, %cars+cdrs, %cars+cdrs+, %cars+cdrs/no-test
```
~We just did that.~ -- (actually, we made them primitives. We *could* inline them, but then we'd need to get them into the core, and make the compiler inline even more primitives...)
There is one single C function `cars_cdrs` that does all the work, and five new internal Scheme primitives.
All procedures in the `fold` family are faster now.
* In `redefine`, get the standard procedures from module `SCHEME`, not `STklos`.
* Don't define `proper-list?`, just make it an alias to `list?`, since they do the same thing, and `list?` is a fast primitive already …

Enhancements and optimizations for SRFI-1

---

lib/object.stk

Some more documentation :)
STklos implements a great object system with a MOP, and I'll try to document it little by little.
Some questions:
* What does `slot-init-function` do? It seems to always return the init form, independent of what argument I pass to it
* Shouldn't `slot-init-function` be called `class-slot-init-function`, since it also takes a class as argument?
* The names `class-direct-supers` `class-direct-subclasses` seem a bit inconsistent.  Shouldn't those be either both abbreviated (`class-direct-supers` `class-direct-subs`) or both extended/complete (`class-direct-superclasses` `class-direct-subclasses`)?

Document MOP

---

doc/hacking/hacking.adoc
doc/refman/idiosync.adoc
doc/vm/vm.adoc
lib/bonus.stk
lib/callcc.stk
lib/compiler.stk
lib/describe.stk
lib/peephole.stk
lib/r7rs.stk
src/boolean.c
src/char.c
src/env.c
src/fport.c
src/hash.c
src/lib.c
src/mutex-common.c
src/number.c
src/object.c
src/print.c
src/sport.c
src/system.c
src/uvector.c
src/vm.c

The guard is around `STk_init_utf8()`, but that function, in
`utf8.c`, already has the same guard:
```c
int STk_init_utf8(void)
{
#ifdef STK_DEBUG
ADD_PRIMITIVE(char_utf8_encoding);
ADD_PRIMITIVE(dump_string);
#endif
return TRUE;
}
```
It seems cleaner to call all init functions in lib.c, and just
include the debug guards around the relevant code chunks, as
is done in `utf8.c`, shown above.
Also fixed a typo in `mutex-common.c`
-----------------
Ok - I also included a lot of small trivial changes after the commit described above...

Small enhancements

---

src/number.c

One more PR... :)
The second one seems interesting, because `bignum2double` is used a lot in the code...
At least for `positive?` and `negative?` there seems to be some speedup - and it seems simpler.
This patch adds only 20 lines of code, and a lot more of comments... :)
Currently, `bignum2double` does not use the function `mpz_get_d` since it gives an unspecified value when converting a number which is `+inf` or `-inf`.
I have verified that it also brings rounding problems: if we use `mpz_get_d`, the resulting double will be rounded *towards zero*, but R7RS requires that we pick the closest number.
If the result does not fit a double, we return $\pm$`inf.0` We don't use the result of `mpz_get_d` because it does not guarantee that an inf will be returned in this case. …

Enhancements to bignums (including a big speedup to `bignum2double` and `exact->inexact`)

---

src/vm.c

The `continue` in the definition of `NEXT` interacts badly with the `do{ ... }while(0)` guard; instead of using `continue`, we put a label at the end of the loop and jump there.
(This is the `goto` version, not the `if` version :)
Fix #528

Fix non-computed-goto build

---

src/number.c
tests/test-number.stk

`STk_Cstr2number` now calls `Cstr2simple_number` twice in order to read the two parts of a complex number...
`Cstr2simple_number` needs to modify some of its arguments, so we pass some pointers to it -- mostly to keep the basis and exactness consistent in the two parts of the number.
This should fix #564

Read complexes with infs and nans

---

src/number.c
tests/test-number.stk

Because the limit when $x \to -\infty$ is actually $+\infty + i\pi$.
Current behavior:
```scheme
(log -0.0)    => -inf.0+3.14159265358979i
(log -10e50)  => 117.431839742696+3.14159265358979i
(log -10e100) => 232.561094392399+3.14159265358979i
(log -10e400) => -nan.0            ;; oops, should be inf + pi.
```
With this patch:
```scheme
(log -10e400) => +inf.0+3.14159265358979i
(log -inf.0)  => +inf.0+3.14159265358979i
```
A test is included.
This patch also corrects the test for `(log -0.0)`, which was ignoring the outcome from two predicates.

`(log -inf.0)` = `+inf + i*pi`

---

lib/bonus.stk
lib/module.stk
lib/runtime-macros.stk
lib/runtime.stk
lib/srfis.stk
src/misc.c
src/number.c
src/read.c
src/signal.c
src/symbol.c
src/vm.c

One is actually relevant:
The documentation of `string->symbol` assumed that STklos is case-insensitive, but today this is optional (and not default).

Small documentation fixes

---

lib/srfi/43.stk
tests/srfis/43.stk

The procedure should augment the vector as necessary, even if there's no fill argument...
```scheme
(define v (make-vector 5 -1))
v => #(-1 -1 -1 -1 -1)
(vector-copy v 0 8)
```
The above currently triggers an error, but SRFI 43 says it should augment the vector with an unspecified argument...
This patch fixes this:
```scheme
(vector-copy v 0 8) => #(-1 -1 -1 -1 -1 #void #void #void)
```

Fix behavior of `vector-copy` in SRFI 43

---

doc/vm/vm.adoc
lib/compiler.stk
src/vm.c

These are mostly patches that add comments to `compiler.stk`, and one which also expands `vm.adoc` a little bit.

More documentation to the compiler and `vm.adoc`

---

src/number.c
tests/test-number.stk

R7RS says it "computes the absolute value of its argument", but doesn't imply it should be real...
So we do compute the norm,
` (abs a+bi)` $`= \sqrt{a^2+b^2} `$
as usual.
A very small patch... :)
```
(abs -3+4i)             => 5
(abs -3.0-4i)           => 5.0
```
Here's a list of how other lisps deal with `(abs -3-4i)`:
| System      | result       | remark           |
|-------------|--------------|------------------|
| Bigloo      | no complexes |                  |
| Biwa        | no complexes |                  |
| Chez        | error        |                  |
| Chibi       | -3-4i        | leaves unchanged |
| Chicken     | error        |                  |
| Cyclone     | error          |  |
| Gambit      | error        |                  |
| Gauche      | 5.0          | …

Make `abs` work for complexes

---

src/number.c

Currently, STklos crashes on this input: `(sqrt 1-0.0i)`.
Looking at the algorithm used, it seems that we can both fix this crash and also make it a bit more precise.
With this PR, we calculate the square root of coplexes as this (same algorithm that Clisp uses):
```
sqrt(a+bi) = A+Bi
if a < 0:
B := sqrt( (|z|-a) /2) * sign(b)
A := b/(2*B).
if a >= 0:
A := sqrt( (|z|+a) /2)
if A != 0:
B := (b / (2*A))
else:
B = 0.0
```
So we don't use `ex2inex`, `angle` (and consequently `atan`) anymore, only two square roots and one inversion (and it seems to be more precise - see below).
A tricky part is to test "a < 0" for negative zero (because -0.0 < 0 won't work, we need to get the `REAL_PART` and use `signbit()` to test it)
Looking at the limiting process, we see that
```scheme …
```

Fix an `sqrt` crash, make it faster and more precise

---

src/number.c
tests/test-number.stk

Because of the way subtraction is performed, the expression `(- 0.0)` turns out to evaluate as `0.0`, because
* `(- 0.0)` becomes `(- 0 0.0)` in `"-"`
* `(- 0 0.0` becomes `(- 0.0 0.0)` in `convert`
* the result is `0.0`
This patch fixes this, so `(- 0.0)` is now `-0.0` (as all Schemes do)

`(- 0.0)` should be `-0.0`

---

lib/mbe.stk
tests/test-macros.stk

Hi @egallesio 
This is about issue #604 --
The current `let-syntax` implementation doesn't work because it calls `%find-macro-clause` with 4 parameters, and a 5th was added.
```
stklos> (let-syntax ((f (syntax-rules () ((f) 10)))) (f))
**** Error:
find-clause: 5 arguments required in call to `#[closure find-clause]' (4 provided)
```
This patch changes `let-syntax` so it takes into account custom ellipsis symbols.

Fix a small glitch in `let-syntax`

---

src/vm.c

```
STKLOS-COMPILER> (compiler-error )
**** Error:
compiler-error: `#[closure compiler-error]' requires at least 3 argument (0 provided)
```
Oops! That should have been plural, "arguments". Turns out it was a thinko when comparing arity.

(tiny fix) Fix plural in error message

---

lib/srfi/27.stk
lib/srfi/Makefile.am
lib/srfi/Makefile.in
tests/srfis/27.stk

It looks like we were missing an `in-module` in the definition of `random-integer` and `random-real`.

Bring back newer SRFI-27

---

lib/bonus.stk
tests/test-misc.stk

I hope I'm not sending too many PRs... :)
I had an idea -- the `apropos` procedure could be enhanced.  I have implemented some additional features:
* More than one module can be passed, so the symbol can be looked up in several modules (and if `#t` is passed, then it is searched in all modules
* Two new variants of the procedure: `apropos/alist` returns an association list that has the symbols categorized by module; and `apropos/pp` returns `#void`, but *prints* a categorized list of modules on the current output port.
* All these procedures accept three keyword parameters, all boolean:
- `:internal` means "look for symbols defined in the module"
- `:imported` means "look for symbols in the module imports"
- `:exported` means "look for symbols exported by the module"
The …

Enhancements to `apropos`

---

lib/repl.stk

* Mention that `ls` accepts usual arguments
* Make `,o` use the `default-browser` procedure (otherwise, at least on my Linux system, it won't work, although I can't see exactly why)

Enhancements to REPL commands

---

tests/test-misc.stk

Not an exhaustive test, which would be too slow, but quite extensive (from $0$ to $2^{12}$).

Extensive check for crashes in `#p`

---

SUPPORTED-SRFIS
lib/srfi/232.stk
lib/srfi/Makefile.am
lib/srfi/Makefile.in
lib/srfis.stk
tests/srfis/232.stk

As I mentioned in PR #602, with a simple modification in `syntax-rules`, the reference implementation of SRFI-232 works!
Passes all tests!
*** This is based on my other branch, from #602, so it's easier to see the changes there first, I suppose.
It exports all its symbols, but currently that's the only thing we can do with macros. 
(In the future, when we make macros reference variables in their defining environment, not their expansion environment, then we could only export the right symbols)

Add SRFI 232 - Flexible Curried Procedures

---

lib/Makefile.am

The Makefile has a rule for `.c.@SH_SUFFIX@`, which includes `@LDFLAGS@`.

Respect LDFLAGS

---

SUPPORTED-SRFIS
lib/srfi/178.c
lib/srfi/178.stk
lib/srfi/Makefile.am
lib/srfi/Makefile.in
lib/srfis.stk
tests/srfis/178.stk

Well...  I thought I'd implement one more SRFI... :grin: 
This is SRFI 178 - Bitvector library.
* Written mostly in C, but with some parts in Scheme
* The reader syntax, '#*', is not implemented, because the reader has no way to know if the SRFI has been loaded.
Regarding this, I see some possibilities:
* Adopt the `bitvector` type as native, and keep only `bitvector`, `bitvector-set!`, `bitvector-ref` in the core, and if the user wants, the rest may be brought with `(import (srfi 178))`.
* Use a global variable `loaded_srfi_178` that tells the reader wether it can read bitvectors. *However* -- the bitvector data structure would not be known to the reader, and the SRFI would at least have to change a function pointer in the reader.
* Don't implement the read syntax (but …

Add SRFI 178 - Bitvector library

---

lib/srfi/178.stk
tests/srfis/178.stk

```
stklos> (import (srfi 178))
stklos> #*11
stklos> (class-of #*11)
Program received signal SIGSEGV, Segmentation fault.
```
This is because `#*11` is of a type which is only defined in `srfi-178.c`, and `object.c` can't tell what it is.
We do as we did in SRFI 25, and customize `class-of` and `describe` for bitvectors.

Customize `class-of` and `describe` for bitvectors

---

lib/bonus.stk
tests/test-number.stk

`exact-integer-log` is to log what `exact-integer-sqrt` is to `sqrt`.
It is actually easy to implement, since
* $\log_b(n) = \log_2(n) / \log_2(b)$.
* `(integer-length n)` $= \lfloor \log_2(n)\rfloor + 1$
We just need to put everything together, noting that $\log_b(n) = \log_2(n)/\log_2(b)$. Actually, we need a small adjustment, since 
```math
\lfloor \log_r(s)\rfloor / \lfloor \log_y(x)\rfloor
\geq
\lfloor \log_r(s) / \log_y(x)\rfloor
```
(That is, it's not always an equality) - but that's easy to do.
Then we'll have this:
```scheme
stklos> (exact-integer-log (+ (expt 7 20000) 5) 49)
10000
5
```

Add `exact-integer-log` (similar to R7RS `exact-integer-sqrt`)

---

src/number.c
tests/test-number.stk

Create a `my_log2` C function, that deals with logs of exact powers of 2. This will give us exact results when the number is exact and the base is a small power of two:
```scheme
(log (expt 8 21) 8) => 21
(log (expt 2 10) 2) => 10
(log 1/4 2)         => -2
(log -4 2)          => 2+4.53236014182719i
```
In the last example, we got an _exact_ real part.
Roughly,
* For fixnums, compare to the known possible powers of two (there are not too many of them anyway)
* For bignums, use `mpz_sizeinbase`
* For rationals, do $\log(x/y) = \log(x) - \log(y)$. This allows us to give exact answers to `(log 1/64 4)`.
But additionally,
* If the base itself is a small power of two, we try to get an exact result anyway: use it in `mpz_sizeinbase` for bignums and use it (the base) to check for known powers for …

Compute exact `log` when base is a power of 2 (also faster)

---

lib/compiler.stk
tests/test-number.stk

Still kind of erratic (got no time for long hacking sessions), but I managed to do this...
* This patch does constant folding to all math expressions, even using transcendentals etc. 
* Creates a compiler option to turn this on and off (`compiler:open-math` -- not a good name... Is there a better one?)
* It also creates a more compact way to create the inline table
* And, well, it's not large at all :)
Do you think it's interesting?
`(exp (sqrt 5))` will end up generating:
```
000:  CONSTANT             0
Constants:
0: 9.35646901660115
```
Another example, with a nested expression:
```
stklos> (disassemble-expr '(cos (+ 3 (tan 2))) #t)
000:  CONSTANT             0
Constants:
0: 0.685897402427631
```
I did this because it's not unusual to write `(expt 2 10)` or other powers …

More power to constant folding :)

---

configure
configure.ac

I'm not an expert in autotools, so maybe there's a more elegant way to do this. Anyway, it would be nice to tell the user in the configure summary if `asciidoctor` was not found...
It won't complain or say anything if ruby-rouge is not installed, but it's already better than not saying anything at all...
```
SUMMARY
*******
System:  Linux-6.5.0-1-amd64
OS nick:  LINUX_6_5
OS type:  unix
Install prefix:  /usr/local
C compiler:  gcc
Compilation flags:  -g -O2
Loader:  ld
Thread support:  pthreads
Case sensitivity:  true (by default)
Control fx parameters:  yes
System libraries used:  libffi libpcre2 libgmp libgc
Compiled libraries:
asciidoctor:  no (documentation will NOT be rebuilt)
```

configure: report if `asciidoctor` was found

---

src/number.c
tests/test-number.stk

Previously we had
```
stklos> (acos 1)
0.0
stklos> (asin 0)
0
```
Hm, we have anice precise result for `(asin 0)`, why not for
`(acos 1)`?   It's because for asin, we have:
```
case tc_integer:  if (z == MAKE_INT(0)) return MAKE_INT(0);
return asin_real(INT_VAL(z));
```
and for acos, we were also testing for exact zero, and then we returned inexact pi/2:
```
case tc_integer:  if (z == MAKE_INT(0)) return div2(double2real(MY_PI),
MAKE_INT(2));
```
But that's not necessary, because `acos_real` will do that anyway. And we were not testing for the nice case of `(acos 1)`. Now we do that.
One test was also adjusted.

Make `(acos 1)` return exact zero

---

src/number.c
tests/test-number.stk

And also `(atan -0.0 0)` => $-\pi/2$
This is explicitly given as a corner case in R7RS (in the table in the section for trigonometric procedures).
We also make `(angle 0)` trigger an error, since this would have to be exactly the same as `(atan (/ 0 0))`, which can't be computed.
Interestingly, only Chez does trigger the same error (for "`(angle 0)`"), but it is conceptually the right thing to do.
Tests included.

Fix `(atan 0.0 0)` => +pi/2

---

src/number.c
tests/test-number.stk

One more small change:  for `(log 1 x)`, if x is neither 0 nor 1, we could just return exact zero...

Make `(log 1 x)` return exact zero

---

lib/bonus.stk

Now we also use plural for zero: "zero bytes" and "zero allocation calls"...
```
stklos> (time 1)
;    Elapsed time: 0.016 ms
;    Allocations: 0 bytes in 0 allocation calls (GC: 0)
1
stklos> (time (list 1 2 3 4))
;    Elapsed time: 0.007 ms
;    Allocations: 96 bytes in 4 allocation calls (GC: 0)
(1 2 3 4)
stklos> (time (list 1))
;    Elapsed time: 0.004 ms
;    Allocations: 24 bytes in 1 allocation call (GC: 0)
(1)
```
But we use singular for one, as in the last example (one "allocation call").

Small enhancement to message

---

lib/bonus.stk
tests/test-misc.stk

Not sure if this reeeealy is interesting, but here it is: it can be useful to make code clearer -- instead of
```scheme
(and (pair? x) (not (list? x)))
```
we can write
```scheme
(improper-list? x)
```

Add `improper-list?`

---

src/stklos.h

1. Fix typo: THEADS_NONE → TH**R**EADS_NONE
2. `THREADS_NONE` is defined in "stklosconf.h"

Fix build with --enable-threads=none

---

lib/compiler.stk

We had this:
```
(let 1 2)
=> #[primitive %execute]
```
because `valid-let-bindings?` would return `#f` and not trigger an error when `bindings` was not a list.
This patch fixes that error, and passes all tests.

Fix `valid-let-bindings?`

---

lib/scheme/list.stk

The reference (sample) implementation had a bug that reversed the arguments to =. The implementation has been corrected to match the SRFI text, and we do so in STklos also.
See:
https://srfi.schemers.org/srfi-1/srfi-1.html#lset%3D-element-equality-order
The difference in behavior is only for side-effects. It can be seen in this example:
```
;; OLD version of lset=
scheme/list> (lset= (lambda (x y) (print x) (= x y)) '(1 2 ) '(1 2 ))
1
2
2
1
2      ;; <= HERE!
2
;; NEW version of lset=
scheme/list> (lset=-new (lambda (x y) (print x) (= x y)) '(1 2 ) '(1 2 ))
1
2
2
1
1      ;; <= HERE!
2
```

Fix `lset=` in SRFI 1 / `(scheme list)` (small issue, side-effects only)

---

lib/module.stk

`(in-module mod symb . default)` will now use `%%in-scheme` when `mod` is `SCHEME`.
```scheme
(macro-expand '(in-module SCHEME list))
=> (apply symbol-value* 'list (find-module 'SCHEME) '())
stklos> (disassemble-expr '(in-module SCHEME list))
000:  PREPARE-CALL
001:  GLOBAL-REF-PUSH      0
003:  CONSTANT-PUSH        1
005:  PREPARE-CALL
006:  CONSTANT-PUSH        2
008:  GREF-INVOKE          3 1
011:  PUSH
012:  NIL-PUSH
013:  GREF-INVOKE          4 4
016:
```
The new code:
```scheme
(macro-expand '(in-module SCHEME list))
=> (%%in-scheme 'list)
stklos> (disassemble-expr '(in-module SCHEME list))
000:  CONSTANT             0
002:  INSCHEME
003:
```
Following is an illustration of the speedup.
```scheme
(time
(let ((a #f))
(repeat 10_000_000
(set! a (in-module SCHEME list))) a))
```
Old …

Optimize `in-module` for `SCHEME`

---

doc/vm/vm.adoc

* The `tick` function mentioned in the stats-gathering documentation is not the one used in the VM (it was a previous version that was never commited to  STklos). This patch includes the correct version;
* The documentation for `%vm-collect-stats` is more clear now;
* Include documentation for `%vm-config`.

enhancements to `vm.adoc`

---

QUICK-INSTALL.md

* Include a more recent version of example of configure report (with the message about asciidoctor)
* Include environment variables and their use in the configure script
* Include `--with-gmp-light` as a synonym for `--with-provided-bignum`

More information in `QUICK-INSTALL.md`

---

tests/test-ffi.stk

We test 'cos':
- so we can test wether shadowing Scheme names is working properly
- and we also test the double <-> real conversion

More FFI tests

---

configure.ac

Like this:
```
Case sensitivity:  true (by default)
Control fx parameters:  yes
System libraries used:  libffi (3.4.6) libpcre2 (10.42) libgmp (6.3.0) libgc (8.2.6)
Compiled libraries:
Documentation update:  yes (since Asciidoctor is installed)
```

Report system library versions

---

configure.ac

It may be useful to immediately see if we're using gcc version 14 instead of 13, for example.
So now there are two lines:
* one for the compiler binary
* one for the version string (1st line reported by the compiler when called with `--version`)

Report C compiler version in configure script

---

lib/compiler.stk

These two situations are similar, but one signals a compiler error, and the other signals an error after copilation:
```scheme
stklos> (/)
**** Error:
compiler-error: /: needs at least one argument
stklos> (/ 2 0)
**** Error:
/: cannot make rational with null denominator
```
With this PR, both are treated similarly.

Detect division by zero when inlining

---

src/number.c
tests/test-number.stk

Currently we always reject bignum exponents, except for when the base is +1.
Before: 
```
stklos> (expt -1 12676506002282294232132132123213213213015)
**** Error:
expt: exponent too big: '12676506002282294232132132123213213213015'
stklos> (expt 1 12676506002282294232132132123213213213015)
1
```
Now:
```
stklos> (expt -1 12676506002282294232132132123213213213015)
-1
stklos> (expt 1 12676506002282294232132132123213213213015)
1
```

Allow for `(expt -1 bignum)`

---

doc/refman/object.adoc
lib/object.stk

I needed the CLOS `initialize-instance` method and couldn't find it, then I found that STklos implements it with the name "`initialize`"... And also found that it wasn't documented yet, so I have written some documentation. Is the explanation I gave OK?

Document `initialize`

---

configure.ac
src/ffi.c
tests/do-test.stk

This PR changes `ffi.c`, `configure.ac` and `do-test.stk` to allow STklos to be compiled without the FFI.
I did this because the FFI lib may not be available in some environments, and also because it may be interesting to have STklos running without the 47k taken by the libffi shared object file...
In particular, I couldn't compile STklos with musl libc in order to run on my wireless router (it used to be possible, but now for some reason it complains about the FFI -- but I don't need it in that context anyway).

Allow STklos to compile without the FFI

---

Makefile.am
doc/pp/Makefile.am
doc/refman/Makefile.am
extensions/Makefile.am
extensions/curl/Makefile.am
extensions/fuse/Makefile.am
extensions/gtklos/Makefile.am
lib/Makefile.am
lib/SILex.d/Makefile.am
lib/scheme/Makefile.am
lib/scheme/vector/Makefile.am
lib/srfi/160/Makefile.am
lib/srfi/Makefile.am
lib/stklos/Makefile.am
lib/streams/Makefile.am
utils/Makefile.am

Otherwise we may end up removing source files when uninstalling.
Should fix #689

Do `(cd DIR && rm ...) || true`

---

configure.ac
lib/bonus.stk

The configure script now tells us the paths. I have actually found one case in which the information was relevant (lib path was set to "/usr/lib/stklos/2.0" but the scheme lib path was set to "/usr/share", and scheme libraries being installed in "/usr/share/stklos/2.0", resulting in a system that cannot load libraries without the need to manually change `load-path`...
```
System libraries used:  ffi (3.4.6) pcre2 (10.42) gmp (6.3.0) gc (8.2.6)
Compiled libraries:
STklos load prefix:  /usr/local
Binary load path:  /usr/local/lib/stklos/2.00
Scheme load path:  /usr/local/share/stklos/2.00
Documentation update:  yes (since Asciidoctor is installed)
```
And `version->alist` will also inform the paths separately:
```
(stklos.binary-load-path "/usr/local/lib/stklos/2.00") …
```

Inform binary and Scheme load paths in configure and SRFI-176

---

INSTALL-cross-compile.md
lib/scheme/Makefile.am
utils/tmpcomp
utils/tmpgenlex

@egallesio : 
I have been cross-compiling STklos for wireless routers (and it works really well - STklos has a very short startup time, and that makes a huge difference on some devices!)
But some recent changes made cross-compilation a bit more difficult. Looking into it, I see it would actually be nice if a few changes were applied to the `Makefile`s and also to `tmpcomp`/`tmpgenlex`.
This is a very small change, but is crucial for cross-compilation.
When the variable `STKLOS_BINARY` is set, it will be used (during cross-compilation, it will be the locally installed stklos); when it is not set, then `${prefix}/src/stklos` is used.
Also, in `tmpcomp`, the prefix was computed as `../`, relative to utils. But in `tmpgenlex` it was hardcoded. This PR also changes `tmpgenlex` to do the same …

Making cross-compilation easier

---

lib/repl.stk

```
stklos> ||
**** Error:
string-ref: index '0' out of bound in string '""'
```
This is because, if the line begins with a symbol, the REPL will try to look into its name to check if it's "!", (a shell command).  But the empty symbol has no chars in its name...
With this PR, the behavior is:
```
stklos> ||
**** Error:
%execute: symbol '||' unbound in module 'stklos'
```

Don't reference char of empty symbol's name

---

configure.ac

1. Don't test `$VAR` against `""`
Instead, do `"X$VAR" == "X"`
2. Don't use `==`, use `=` for comparing strings.
This *seems* to *partially* fix the current Android compilation problems...
Actually, the Android problems remain, but with this PR, passing data and lib dir doesn't seem to be necessary (the report in the final step of configure is correct).
But it still fails to load readline.

More portable use of test in configure.ac

---

src/mutex-pthreads.c
src/stklos.h
src/thread-pthreads.c

I'm not actually sure about the first change. @egallesio what do you think?
* Use `void *code` instead of `SCM (*code)()` in `struct primitive_obj`, so GCC won't check types (it's just a void pointer now).
* Use `SCM` for the arguments to pthreads functions.
Passes all tests.

Make STklos compile with GCC-15

---

src/read.c

Fixes the following segfault:
```
stklos> #,()
Program received signal SIGSEGV, Segmentation fault.
0x00005555555a66e3 in read_srfi10 (port=0x7ffff7441840, l=0x3) at read.c:1217
1217	  tmp = STk_int_assq(CAR(l), ctor_table);
(gdb) where
#0  0x00005555555a66e3 in read_srfi10 (port=0x7ffff7441840, l=0x3) at read.c:1217
#1  0x00005555555a5fea in read_sharp (port=0x7ffff7441840, ctx=0x7fffffffdae0, inlist=0) at read.c:987
#2  0x00005555555a62ee in read_rec (port=0x7ffff7441840, ctx=0x7fffffffdae0, inlist=0) at read.c:1078
#3  0x00005555555a64c3 in read_it (port=0x7ffff7441840, case_significant=1024, constant=1) at read.c:1150
#4  0x00005555555a653a in STk_read_constant (port=0x7ffff7441840, case_significant=1024) at read.c:1167
#5  0x000055555559dd4a in STk_scheme_read_cst …
```

Do not take `CAR` of `()` in " `#,()` "

---

src/hash.c
src/hash.h
src/symbol.c
tests/test-misc.stk

```scheme
(define aaa 1)
(symbol-interned? (string->uninterned-symbol  "aaa"))   => #f
(symbol-interned? (string->uninterned-symbol  "aaaaa")) => #f
(symbol-interned? (gensym))                             => #f
(symbol-interned? 'a)                                   => #t
(symbol-interned? 'aaa)                                 => #t
```
Inspired by a discussion on the SRFI-258 mailing list.

[simple] Add `symbol-interned?`

---

lib/r7rs.stk
src/boolean.c
tests/test-r7rs.stk

Currently, if one of the symbols is uninterned, `eqv?` may consider both to be the same. With this patch, `eqv?` won't deal with uninterned symbols, treating them always as "different from whatever else".
This is the same behavior as Chez, Chicken, Gambit, Gauche, MIT, ypsilon. (Bigloo, Kawa, Chibi do not have string->uninterned-symbol).
The change is:
1. In `eqv?`, check for hard equality (with `==`) so if one of the symbols is uninterned, the result is `#f`
2. Since we're at it, rewrite `symbol=?` so it will not accept non-symbol arguments (so its behavior will be the same as `string=?`
So now:
```scheme
(eqv? (string->uninterned-symbol "x")
(string->uninterned-symbol "x"))       => #f
```
This should fix #709

Make `eqv?` and `symbol=?` agree.

---

src/read.c

* We now tell the user what closing delimiter was found -- `(` `[` or `{`.
* If we were reading a list then we also inform what closing delimiter was expected instead.
Examples:
```
stklos> '[a)
**** Warning:
bad closing parenthesis `)` (expected `]`) on line 1 of '#[input-virtual-port 7ff782c93840]'
(a)
stklos> 123 ]
123
**** Warning:
bad closing parenthesis `]` on line 3 of '#[input-virtual-port 7f5fa526b840]'
```

[simple] Be more informative about the 'bad closing parenthesis'

---

src/list.c

1. Do not pass non-lists to `STk_int_length()`  (why did it never crashed before?)
2. Explain that the length of a list is not calculable because it is improper.
Now we have:
```
stklos> (length '(a . b))
**** Error:
length: length of improper list '(a . b)' is not calculable
stklos> (length 'a)
**** Error:
length: bad list a
```
In both cases, the behavior was (before) to say that "length of ... is not calculable". And STk_int_length was called in non-lists.

[trivial] `length`: reject bad lists, and be more informative

---

lib/srfis.stk

@egallesio we should probably have a script to update this from the SRFI site: https://github.com/scheme-requests-for-implementation/srfi-common/
This is the file wit SRFI data:
https://raw.githubusercontent.com/scheme-requests-for-implementation/srfi-common/master/admin/srfi-data.scm
Maybe:
1. Only store the number of implemented SRFIs in a list, `(define implemented-srfis '(0 1 2 4 ...))`
2. Have the compiler fetch the data from the site
3. Have a version of the SRFI data within STklos source, to be used when (2) doesn't work (due to lack of network access for example)
What do you think?

[trivial] Update `srfis.stk`

---

src/system.c

See issue #745 . 
`exit` should never signal errors, and it should actually exit (never get back to the REPL or to the program).
Bigloo, Chibi, Chez, Cyclone, Gauche, Guile never signal errors or return from `exit`. They all ignore the second argument, and will exit the program regardless of the type of the first argument.
Chicken will only signal an error for wrong type. For several arguments, so long as the first  is an integer, it does exit the program. But it does not accept booleans (?)
Loko, MIT Scheme and Sagittarius only signal an error for too many arguments. They will exit when the single argument is not a number.
Kawa and Gambit behave as STklos today (signal erorrs for too many arguments, and for wrong type).
Biwa and LIPS don't have an `exit` procedure.

[simple] Make exit be as per R7RS

---

lib/compiler.stk

```
stklos> (disassemble-expr '(* a 2))
000:  GLOBAL-REF           0
002:  IN-SINT-MUL2         2
004:  INT-PUSH             2
006:  GLOBAL-REF           0
008:  IN-MUL2
```
We're compiling twice!
This is because of a wrongly put parenthesis in `compiler.stk`:
```scheme
((*)  (case len
((0)  (emit 'IM-ONE))
((1)  (if (number? (car actuals))
(compile (car actuals) env epair tail?)
(compile-normal-call fct actuals len env epair #f)))
((2)  (let ((a (car actuals))
(b (cadr actuals)))
(if (small-integer-constant? a)
(oper2 'IN-SINT-MUL2 b a))
(comp2 'IN-MUL2)))                 ;; OOPS! Will be recompiled always!
(else (compile-normal-call fct actuals len env epair #f))))
```
In the above example, (comp2 'IN-MUL2) was supposed to be the alternative for the IF, but it is outside it, so will …

[simple] Fix double compilation of multiplication

---

lib/module.stk
lib/r7rs.stk
lib/scheme/list.stk
lib/scheme/vector/tagvector-template.stk
src/list.c
src/proc.c
src/stklos.h
src/str.c
src/system.c
src/vector.c

These are several enhancements to `list.c` and related functions in `proc.c`.
Passes all tests. :)
And there are some really big performance gains, besides some enhancements in argument checking and error messages. (This brings the new allocator for lists, which does not repeatedly cons, but asks for a large set of cells each time)
Allocate more cells at once in `make-list`.
`libgc` only offers an interface to "get several objects", without telling us how many. It's usually a not very large number like 128 objects for example). We give the size, and receive a list.
This patch does this:
1. Implements `SCM STk_must_malloc_list(int n, SCM init)` that will allocate a list of CONS cells.
2. Changes `vector->list` so it will use the new function
3. Removes `make-list` and use …

Optimize `list.c`

---

lib/describe.stk

- Don't use exception handling to detect immutability (we bave a primitive for that!)
- Say when the symbol is uninterned.

[simple] Enhance describe for symbols

---

lib/describe.stk

- `,d (+ +nan.0 0+3i)` now works poperly (this currently signals an error)
- describe the number type of numerators, denominators, real parts and imaginary parts

[simple] Better describe for complexes, rationals

---

src/vm.c

This makes processing of variable args faster.
```scheme
(import (scheme list))
(define (f . rest) 1)
(define-macro (call-f-with-500-args)
(append '(f) (iota 500)))
(time (repeat 100000 (call-f-with-500-args)))
```
Old code:
2130.932 ms
50000000 allocation
New code:
1660.077 ms
100000 allocation
```scheme
(define-macro (call-f-with-2-args)
(append '(f) (iota 2)))
(time (repeat 10000000 (call-f-with-2-args)))
```
Old code:
1256.636 ms
20000000 allocation
New code:
1159.518 ms
10000000 allocation

[simple] Use `STk_C_make_list` in `listify_top`

---

lib/runtime-macros.stk

Runs perfectly without it...
`|lamdba|` $\longrightarrow$ `lambda`

[trivial] Remove bars from lambda in runtime macro definition

---

tests/test-macros.stk

* Some tests for lexical scope (all passing)
* Some tests for macros remembering their environment and module (not passing, all commented out)

[simple,R7RS] More macro tests

---

src/number.c
tests/test-number.stk

Currently:
```
stklos> (+ +)
#[primitive +]
stklos> (+ "a")
"a"
stklos> (* "a")
"a"
```
With this PR the type check is being performed.
instead of "bad number" we report "cannot operate", so the behavior is consistent with that of `/` and `-`:
```
stklos> (/ "x")
**** Error:
/: cannot perform division on '1' and '"x"'
stklos> (* "x")
**** Error:
*: cannot perform multiplication on '1' and '"x"'
stklos> (- "x")
**** Error:
-: cannot perform difference on '0' and '"x"'
stklos> (+ "x")
**** Error:
+: cannot perform addition on '0' and '"x"'
```

[simple,R7RS] Fix unary sum and multiplication

---

lib/r7rs.stk
src/list.c

@egallesio after the other PR for lists is dealt with, then we could perhaps have also a `list-immutable!` procedure. But it would be better to use the new C function that works on circular lists.

Pair immutability and `(features)`

---

lib/scheme/bytevector.c
tests/lib/scheme/bytevector.stk

We had this situation:
```scheme
stklos> ,i scheme/bytevector
stklos> (define b  (make-bytevector 16 -127))
;; b
stklos>  (bytevector-uint-set! b 0 (- (expt 2 128) 3) (endianness little) 16)
stklos> ,d (bytevector-sint-ref b 0 (endianness little) 16)
-3 is a bignum integer number.
```
With this PR, the number is made into a fixnum (which it is!)
This addresses the problem described in PR #768

Turn `mpz_t` into `long` if possible, reading from bytevector; also let `bytevector-uint-set!` accept fixnums

---

lib/scheme/bytevector.c
tests/lib/scheme/bytevector.stk

And provide tests...
The method for setting negative bignums in a K-byte region is to wrap around the range by adding the range itself to the number (this is necessary because `mpz_export` only knows magnitudes, not signals).

Add `bytevector-sint-set!`, which was missing from `(scheme bytevector)`.

---

lib/srfi/13.stk

They're already in the core, as primitives, and their signatures are identical.
Passes all tests. :)

[simple] Don't redefine some string procedures in SRFI-13

---

src/number.c

We now say
- "not a real number", when it's complex, or
- "is a bad number" when it's not a number at all.
Before, we had:
```scheme
(numerator 1.0-2i)
**** Error:
numerator: '1.0-2i' is a bad number
```
But `1.0-2i` *is* a number...
*Remark*: actually R7RS says the argument should be a rational. But in a computer using the IEEE format (for `double`) or other formats (GMP, `long`), all numbers are rationals. So we *can* return the numerator and denominator for "reals"...

[trivial] Better error message for `numerator`/`denominator`

---

src/cpointer.c
tests/test-ffi.stk

```scheme
(define buff (allocate-bytes 5))
(cpointer-set! buff :uchar #\a 0)
(cpointer-set! buff :uchar #\B 1)
(cpointer-set! buff :uchar #\c 2)
(cpointer-set! buff :uchar #\D 3)
(cpointer-set! buff :uchar #\null 4)
(cpointer->string buff)    => "aBcD"
(cpointer->string buff 2)  => "aB"
(cpointer->string buff -1) => error
```

[simple] Add a length parameter to `cpointer->string`

---

src/cpointer.c
tests/test-ffi.stk

These have offset of exactly one byte.

Add  `cpointer-{ref-abs/set-abs!}`

---

src/number.c
tests/srfis/144.stk
tests/test-number.stk

This patch fixes the following problem:
```
stklos> (quotient -inf.0 2)
Floating point exception
stklos> ,i scheme/flonum
stklos> (flodd? +inf.0)
Floating point exception
```
and includes tests.

[simple] Fix crash on integer division with infinities

---

lib/mbe.stk
tests/test-macros.stk

In Section 4.3.2 of R7RS (page 23 of the PDF), it is said that a <template> can be one of:
1. `(<element> ...)`
2. `(<element> <element> ... . <template>)`
3. `(<ellipsis> <template>)`
4. `#(<element> ...)`
Number (3) is an escaping pattern. Inside ir, ellipses are treated like a symbol, and not like the syntax-rules ellipsis. And that template *must* have only two elements.
`(<ellipsis> <template>)`
should be transformed into
`<template>`
but protecting the ellipses (they have no special meaning there).
So
```
(... a)          => a
(... (a b ... c) => (a b ... c)
(... ...)        => ...
(... a b)        => error (too many elements)
```
but the ellipses on the right side are ignored by `syntax-rules`.
The implementation is:
1. In MBE, include a check for malformed escapes (as in the last …

[R7RS] Implement ellipsis escaping, as per R7RS
